### ISSUE TITLE
thin does nothing to yeilded values in EnsembleSampler.sample()

### ISSUE THREAD

**Issue by jeremysanders** [dfm/emcee#104]
If the thin argument is given to the EnsembleSampler.sample() method, it only applies to the stored data, not the values yielded by the generator. This is rather confusing as the docs say otherwise "If you only want to store and yield every thin samples in the chain, set thin to an integer greater than 1."  It might be difficult to change the behaviour without breaking compatibility (does anything rely on this broken behaviour?), but the documention should be changed at least.

**Comment by itcarroll** [comment]
I would also like to see a fix for this ... one (#105) is already waiting to be pulled.
