### ISSUE TITLE
MPI crashes on Ubuntu 14.04

### ISSUE THREAD

**Issue by FedericoV** [dfm/emcee#112]
Hi,

I was testing the simple mpi example included in emcee, and it was causing a crash with this message:

  File "mpi_test.py", line 23, in <module>
    pool.wait()
  File "/home/federico/anaconda/lib/python2.7/site-packages/emcee-2.1.0-py2.7.egg/emcee/mpi_pool.py", line 95, in wait
    task = self.comm.recv(source=0, tag=MPI.ANY_TAG, status=status)
  File "Comm.pyx", line 1175, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:99438)
  File "msgpickle.pxi", line 263, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:39179)
mpi4py.MPI.Exception: Other MPI error, error stack:
MPI_Probe(113).....................: MPI_Probe(src=0, tag=MPI_ANY_TAG, MPI_COMM_WORLD, status=0x7fff1c5cd0b0) failed
MPIDI_CH3I_Progress(461)...........: 
MPID_nem_handle_pkt(636)...........: 
MPIDI_CH3_PktHandler_EagerSend(606): Failed to allocate memory for an unexpected message. 0 unexpected messages queued.
Fatal error in MPI_Finalize: Other MPI error, error stack:
MPI_Finalize(281)..................: MPI_Finalize failed
MPI_Finalize(209)..................: 
MPID_Finalize(117).................: 
MPIDI_CH3U_VC_WaitForClose(383)....: an error occurred while the device was waiting for all open connections to close
MPIDI_CH3I_Progress(461)...........: 
MPID_nem_handle_pkt(636)...........: 
MPIDI_CH3_PktHandler_EagerSend(606): Failed to allocate memory for an unexpected message. 0 unexpected messages queued.

This is on Ubuntu 14.04, using anaconda, and after a freshly built mpi4py where every single test passed without any failures.  Any clue what might be causing this?

**Comment by rodluger** [comment]
Has anyone else run into this? I get almost the exact same error message. I'm on Red Hat 6.6 with a newly installed anaconda. I am running rather large chains with ~100 dimensions, 500 walkers and 100,000 steps, and I run into this error once or twice per run. I save the chain to disk and reset it every 10,000 steps, so I'd be surprised if this was a memory issue. Any help would be appreciated!

```
File "/usr/lusers/rodluger/anaconda/lib/python2.7/site-packages/emcee/mpi_pool.py", line 95, in wait
  File "run.py", line 92, in Run
    pool.wait()                                                                     
  File "/usr/lusers/rodluger/anaconda/lib/python2.7/site-packages/emcee/mpi_pool.py", line 95, in wait
        task = self.comm.recv(source=0, tag=MPI.ANY_TAG, status=status)
    task = self.comm.recv(source=0, tag=MPI.ANY_TAG, status=status)
  File "Comm.pyx", line 816, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:66815)
  File "Comm.pyx", line 816, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:66815)
task = self.comm.recv(source=0, tag=MPI.ANY_TAG, status=status)
  File "Comm.pyx", line 816, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:66815)
    task = self.comm.recv(source=0, tag=MPI.ANY_TAG, status=status)
  File "Comm.pyx", line 816, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:66815)
  File "pickled.pxi", line 236, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:27858)
  File "pickled.pxi", line 236, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:27858)
  File "pickled.pxi", line 236, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:27858)
  File "pickled.pxi", line 236, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:27858)
mpi4py.MPI.Exceptionmpi4py.MPI.Exceptionmpi4py.MPI.Exception: : Other MPI error, error stack:
MPI_Probe(113).....................: MPI_Probe(src=0, tag=MPI_ANY_TAG, MPI_COMM_WORLD, status=0x7fff02e2cb50) failed
MPIDI_CH3I_Progress(432)...........: 
MPIDI_CH3_PktHandler_EagerSend(606): Failed to allocate memory for an unexpected message. 0 unexpected messages queued.
: Other MPI error, error stack:
MPI_Probe(113).....................: MPI_Probe(src=0, tag=MPI_ANY_TAG, MPI_COMM_WORLD, status=0x7fff2c96a520) failed
MPIDI_CH3I_Progress(432)...........: 
MPIDI_CH3_PktHandler_EagerSend(606): Failed to allocate memory for an unexpected message. 0 unexpected messages queued.
Other MPI error, error stack:
MPI_Probe(113).....................: MPI_Probe(src=0, tag=MPI_ANY_TAG, MPI_COMM_WORLD, status=0x7fff45daf9d0) failed
MPIDI_CH3I_Progress(432)...........: 
MPIDI_CH3_PktHandler_EagerSend(606): Failed to allocate memory for an unexpected message. 0 unexpected messages queued.
mpi4py.MPI.Exception: Other MPI error, error stack:
MPI_Probe(113).....................: MPI_Probe(src=0, tag=MPI_ANY_TAG, MPI_COMM_WORLD, status=0x7fff292b4220) failed
MPIDI_CH3I_Progress(432)...........: 
MPIDI_CH3_PktHandler_EagerSend(606): Failed to allocate memory for an unexpected message. 0 unexpected messages queued.
```

**Comment by darmok47** [comment]
I get the same message,
Traceback (most recent call last):
  File "emcee_mpi_benchmark.py", line 28, in <module>
    pool.wait()
  File "/opt/local/anaconda/anaconda-2.2.0/lib/python2.7/site-packages/emcee/mpi_pool.py", line 95, in wait
    task = self.comm.recv(source=0, tag=MPI.ANY_TAG, status=status)
  File "MPI/Comm.pyx", line 1192, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:106889)
  File "MPI/msgpickle.pxi", line 266, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:42711)
mpi4py.MPI.Exception: Other MPI error, error stack:
MPI_Probe(113).....................: MPI_Probe(src=0, tag=MPI_ANY_TAG, MPI_COMM_WORLD, status=0x7fff794b88f0) failed
MPIDI_CH3I_Progress(461)...........: 
MPID_nem_handle_pkt(636)...........: 
MPIDI_CH3_PktHandler_EagerSend(606): Failed to allocate memory for an unexpected message. 0 unexpected messages queued.

is getting annoying

**Comment by darmok47** [comment]
In my case I found that is sensitive on the number of walkers.
If I use nwalkers = 250 and 2 processes I get the error.
If I set nwalkers=200 instead it run flawlessly (though is slower than in the scalar case)

**Comment by manodeep** [comment]
Do you get the same crash if you add `loadbalance=True` while creating the `MPIPool` object?

(Replace `MPIPool()` with `MPIPool(loadbalance=True)`)

**Comment by darmok47** [comment]
yes

**Comment by manodeep** [comment]
Will you please post a minimal set of code to reproduce the problem, including the command-line to run `emcee`.

**Comment by darmok47** [comment]
`from __future__ import print_function

import sys
import numpy as np
import emcee
from emcee.utils import MPIPool
import time
import mpi4py.MPI as MPI


def lnprob(x):
    return -0.5 * np.sum(x ** 2)


#check if mpi is running
if_mpi = (MPI.COMM_WORLD.Get_size() > 1)
# Initialize the MPI-based pool used for parallelization.
if (if_mpi) :
    pool = MPIPool(loadbalance = True)
    print('rank',pool.rank,'size',pool.size)

    if not pool.is_master():
        # Wait for instructions from the master process.
        pool.wait()
        sys.exit(0)


ndim = 50
nwalkers = 250
burnin=100
step=1000
p0 = [np.random.rand(ndim) for i in xrange(nwalkers)]
print('after pool')
# Initialize the sampler with the chosen specs.
tp=time.time()
if (if_mpi):
    sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, pool=pool)
else:
    sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob)

pos, prob, state = sampler.run_mcmc(p0, burnin)

sampler.reset()

sampler.run_mcmc(pos, step, rstate0=state)
if (if_mpi):
    pool.close()

print(u"Mean acceptance fraction: ", np.mean(sampler.acceptance_fraction))
`

I launch it with mpirun -np 2 python femcee_mpi_test.py

if i set nwalkers to 200 no problem
if i set nwalkers to 250 i get

> 
Traceback (most recent call last):
  File "emcee_mpi_test.py", line 57, in <module>
    sampler.run_mcmc(pos, step, rstate0=state)
  File "/opt/local/anaconda/anaconda-2.2.0/lib/python2.7/site-packages/emcee/sampler.py", line 157, in run_mcmc
    **kwargs):
  File "/opt/local/anaconda/anaconda-2.2.0/lib/python2.7/site-packages/emcee/ensemble.py", line 259, in sample
    lnprob[S0])
  File "/opt/local/anaconda/anaconda-2.2.0/lib/python2.7/site-packages/emcee/ensemble.py", line 332, in _propose_stretch
    newlnprob, blob = self._get_lnprob(q)
  File "/opt/local/anaconda/anaconda-2.2.0/lib/python2.7/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/opt/local/anaconda/anaconda-2.2.0/lib/python2.7/site-packages/emcee/mpi_pool.py", line 207, in map
    tag=MPI.ANY_TAG, status=status)
  File "MPI/Comm.pyx", line 1192, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:106889)
  File "MPI/msgpickle.pxi", line 266, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:42711)
mpi4py.MPI.Exception: Other MPI error, error stack:
MPI_Probe(113).....................: MPI_Probe(src=MPI_ANY_SOURCE, tag=MPI_ANY_TAG, MPI_COMM_WORLD, status=0x7ffef96696c0) failed
MPIDI_CH3I_Progress(432)...........: 
MPIDI_CH3_PktHandler_EagerSend(606): Failed to allocate memory for an unexpected message. 0 unexpected messages queued.

**Comment by manodeep** [comment]
Thanks for posting the code fragment - nothing in the code immediately jumps out to me. 

Is it possible that there are multiple `MPI` installations and `mpi4py` was compiled with a different `MPI` implementation than what `mpirun` on the command-line directly refers to. Easiest way to check would be to replace `python` with the `python-mpi` within the `mpi4py/bin` directory. Next step might be to reinstall `mpi4py` via your package manager.

**Comment by themiyan** [comment]
Has there been any developments in this issue? I too get the same error and it seems somewhat random in nature.
What I mean buy this is if I fit 5 objects with same parameters 2 would execute fine and 3 would fail with this error. 

@manodeep mpi4py has been installed within a conda venv in g2. This fails as a queue job and even in the interactive node in g2.

**Comment by manodeep** [comment]
Seemingly random failures *sigh*. I had dug around previously for this issue but did not find any promising avenues.

@themiyan do you want to come by my office and we can debug this issue? Hopefully we can get to the bottom of this. May be we can squash this issue once and for all.

**Comment by joergdietrich** [comment]
I encountered the same problem and concluded that this is an mpi (or rather mpi4py) problem. This is also occurred on a conda installation of mpi4py. The solution in my case was

```
conda remove mpi4py
conda config --add channels conda-forge
conda install mpi4py
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/moon/dietrich/applications/anaconda3/envs/py27:

The following NEW packages will be INSTALLED:

    mpi4py: 2.0.0-py27_2 conda-forge
    mpich:  3.2-4        conda-forge

Proceed ([y]/n)? 
```
The new mpich seems to have solved this for me.

**Comment by manodeep** [comment]
Thanks @joergdietrich - the problem does seem to be the `mpich` bit of `mpi4py`. We figured that a different mpi4py for the platform should do the trick. For @themiyan case, this will most likely require something like `conda install -c mpi4py openmpi=2.0.2`
