### ISSUE TITLE
Memory leak when using mpi_pool loadbalance

### ISSUE THREAD

**Issue by tomlouden** [dfm/emcee#117]
Hi,

I'm running emcee on a small cluster of workstations with openmpi. I find that enabling the Loadbalancing option gives a significant speed boost to my code, but it does so at the expense of the memory footprint growing quite quickly until the program crashes. This is not an issue when Loadbalancing is set to False, so I don't think it's a problem with my own code. I'm not entirely sure what could be going on.
Any pointers?

Thanks

**Comment by dfm** [comment]
The next version of emcee won't include an MPIPool (partly because of this unresolved issue). We're recommending that users switch to https://github.com/adrn/schwimmbad instead.
