### ISSUE TITLE
Possible R package?

### ISSUE THREAD

**Issue by xiaoweiz** [dfm/emcee#119]
I presume the core computation is done in C++. Is there a plan to write a R wrapper around it using [Rcpp](http://cran.r-project.org/web/packages/Rcpp/index.html) to formulate a R package?

**Comment by drknexus** [comment]
See also package:reticulate (https://github.com/rstudio/reticulate).  rPython is venerable, but very bare bones and fails to support virtualenvs.  Other notable entries in the space include PythonInR and [XRPython](https://cran.r-project.org/web/packages/XRPython/index.html).
