### ISSUE TITLE
Daemon Threads with Ensemble sampler not terminating.

### ISSUE THREAD

**Issue by mclaughlin6464** [dfm/emcee#123]
I was running some code where I iterated over ~1000 objects, and performed an emcee sample on each. Each iteration generated a new sampler, but the previous one should have been collected so there should've been no issue. However, I noticed I was having a memory leak, and after much digging I found that there was a daemon thread running that kept a reference to the sampler's pool attribute. I called sampler.pool.terminate() after the run_mcmc call and the leak vanished. I don't know what would be the cause, but it was causing my job to crash after ~80 iterations on a machine with 16GB memory.

**Comment by mikelum** [comment]
I am also seeing a substantial memory leak between individual sampler runs. The problem manifests as N idle threads of approx 1Gb each (I have a nasty space...), where N is (about) number of threads+number of walkers.
My problem is 100% reproducible, but each sample takes about 20hrs to run. I'm going to see if the sampler.pool.terminate() call helps, and if so, will check your branch. I should have more info next week.

**Comment by eteq** [comment]
Awesome, looking forward to hearing back, @mikelum
