### ISSUE TITLE
Using an ensemble sampler within a Gibbs step

### ISSUE THREAD

**Issue by jonathansick** [dfm/emcee#134]
After talking to @davidwhogg about hierarchical modelling and Gibbs sampling at @astrohackweek, I've got some implementation questions.
#1. Can ensemble samplers be used in both/all phases of a Gibbs step?

For example, I have ensemble samplers for parameters local to each pixel. Each sampler has _N_w_ walkers. Now how do I pass the last step from the pixel samplers on to the next phase that samples in global parameters? Specifically, what goes in the `args` to the `run_mcmc` method? I see two options:
1. Just take the state from a single walker (the first one? or a random one?) and pass that on to the global sampler.
2. If the ensemble samplers at the local and global levels both have _N_w_ walkers then I could 'align' the walkers of each. Hence the final state of walker _i_ at the local level would be used by walker _i_ at the global level. I think this is more appealing _but_ is means that I'd need some way of telling the posterior function which walker it belongs to so it can choose the appropriate parameters from the _args_. @dfm, is there already a way to do this?

Or is it A Bad Idea :tm: to use an ensemble sampler within Gibbs (as I think @dfm alluded in #106, though @davidwhogg seemed optimistic)?
#2. How can ensemble samplers be used as a step with a non-ensemble sampler in another step?

If I use an ensemble level for one level of the Gibbs step and a Metropolis-Hastings in another, what parameters do I pass on to MH? Do I always take the parameters at the last step of the i-th walker? Or pick a random walker? (This question mirrors option 1 from above).
#3. Is it a special case to have an ensemble sampler step go into a trivial Gaussian Process step?

As @davidwhogg pointed out, in one of my global Gibbs phases I can make a sample from a normal distribution defined by model-observation residuals. In computing these residuals, should I:
1. marginalize over the models of all walkers to make a single new sample
2. just pick a single walker to make a single new sample, or
3. make a new value for each walker (which means that again, the posterior function for the ensemble sampler at the next level would need to know what walker it belongs to).

(This is a question directed mostly to @davidwhogg and @dfm but anyone is welcome to chime in!)

**Comment by RuthAngus** [comment]
@jonathansick what did you end up settling on?

**Comment by jonathansick** [comment]
Hey @RuthAngus, I ended not using Emcee and instead just implemented my own Metropolis-Hastings in Gibbs (contrary to everyone's advice to look for another off-the-shelf solution ;) ).

In my problem with modeling the stellar population in N pixels, with a background parameter that applies to all pixels I do this:

1. For each stellar population parameter of each pixel, I do an MH step to propose a new parameter. So at least I can do my N pixels in parallel, but the MH step is always a single parameter.
2. When the stellar population parameters of each pixel are all updated, I go up a level and estimate a new background. It turns out that I just need a linear estimator for this.
3. Using the new background parameter, I go back to the pixel level and serially do MH steps again through stellar population parameters of each pixel.
4. Re-estimate background level, and repeat.

This ends up being very simple to implement and was really all I needed. I'm not sure if every project could afford to break up their multi-parameter steps into a series of single parameter MH steps, but it worked for me.

**Comment by davidwhogg** [comment]
Contra @jonathansick's advisors, @RuthAngus I don't think it is a bad idea to build our own. It is fun, and you learn something! But I disagree with @dfm that you *can't* use *emcee*. You just have to choose one value from one walker and use that when you go to the next stage. That is, abandon ensembly-ness at the end of each *emcee* run. It will be inefficient maybe, but because it obviated tuning, it might still be cool.

**Comment by guillochon** [comment]
@davidwhogg I've been reading the back-and-forth debate on [this thread](http://andrewgelman.com/2017/03/15/ensemble-methods-doomed-fail-high-dimensions/) intently. Obviously the stan peeps have...biases, but the orange-skin problem seems difficult to solve in an ensemble sampler, Huijser's paper suggests that emcee (at least vanilla) is kinda useless for n > 10 (sorry, but 100,000+ steps is not feasible). Gibbs seems like one way to salvage the ensemble samplers, if it can be implemented in a mathematically-consistent way.

What if all walker proposals are locked to only a subset of the variables at each step? This sort of addresses the dimensionality problem, all walkers could move in one direction much more easily (towards the edge of the orange).

**Comment by dfm** [comment]
This is no longer affine invariant and only correct with no covariances. Be careful to check any methods you invent with someone who knows how to prove these things (that person is not me!).

**Comment by guillochon** [comment]
I just checked with variances drawn between 1 and 10^6 for all dimensions (i.e. some dimensions are much longer than others). Still the same convergence properties, and the variances in each dimension are recovered:

![image](https://cloud.githubusercontent.com/assets/4998058/24327954/834b4190-11ab-11e7-8f78-5072fa9f72c6.png)

![image](https://cloud.githubusercontent.com/assets/4998058/24327958/a85eefae-11ab-11e7-8069-8f11844aba7e.png)

I've also tested this on a real-world problem and have gotten excellent convergence.

The part about only working with no covariances is interesting. I'll test that.

**Comment by dfm** [comment]
I'm not sure about whether or not it will work but I do know that the proof of the stretch move requires all walkers to be sampling from the same distribution which will _only_ be true if there are no covariances. Even if you have a demo that appears to get the right answer you should make sure that you can prove it!

**Comment by guillochon** [comment]
The algorithm is actually fairly simple, you can imagine it like a single step of emcee where F of the N dimensions are randomly frozen, where the set of thawed dimensions is the sample for all proposals. If a single step of emcee maintains detailed balance, then so should this algorithm. Or are you saying that the vanilla emcee does not work in the presence of covariances either?

**Comment by dfm** [comment]
I understood your proposal and I've definitely thought about it before but it's wrong. emcee is only correct if you propose in all dimensions simultaneously. Your proposed method isn't correct because the different walkers have different values in the _frozen_ dimensions.

**Comment by guillochon** [comment]
I've tested this with covariances now too. Seems to recover them, at least as well as vanilla. However I see your point on the covariances in regards to the frozen dimensions, although I am not sure why it still works with the covariances added. I'll have to think about it a bit more carefully.

**Comment by guillochon** [comment]
So, to recap: We have a method here that: 1. Converges much faster than vanilla in many dimensions (I've tested up to 400 in a small Mathematica notebook), which address the major criticism of the stretch-move raised by the Stan folks. 2. Accurately recovers variances and covariances in models much faster than vanilla as well. *But* 3. Isn't mathematically proven to preserve detailed balanced, and most likely doesn't for a single step. I have the feeling that the method _approximately_ preserves detailed balance: for any given single step you are technically violating it, but given that a random fraction of the dimensions are randomly frozen each step and you cycle through any dimension on average every other step, you are probably very very close to detailed balance.

I have compared the posterior distributions in 100 dimensions to the expectations and they are spot on, even if the dimensions have wildly different scales. With covariances, both vanilla emcee and this new method choke if the variances have wildly different scales, but both seem to do OK if the scales aren't too different from one another. This might just be an issue of needing more walkers with strong covariances.

If you can't calculate the derivatives analytically, HMC methods are going to be approximate anyway, as you're going to have to use finite differences to evaluate derivatives. So I'm not sure I see the big deal in the approximate nature of the Gibbs-like stretch-move if approximate methods are all that one has available in the first place. And given the simplicity of emcee versus something like Stan, the choice seems pretty obvious for a black box problem.

**Comment by guro86** [comment]
Hello, I have a hierarchical problem and am intrigued by using a Gibbs sampler with an inner MH (or emcee) step. I see that you have been discussing this problem since a while back. Does anyone have any example implementation to share? @guillochon, you mentioned that you had success with this, do you still have the code to share? 

I really appreciate any help you can provide.
