### ISSUE TITLE
Discrete Variables in emcee

### ISSUE THREAD

**Issue by lfloeer** [dfm/emcee#150]
Hi,

First of all: Thanks for all the great work put into **emcee**!

I was wondering whether it would be possible to sample discrete variables with emcee. I have created a small example script that estimates the number of trials and probability of success for a binomial distribution here https://gist.github.com/lfloeer/d8a2d3ccc8898eeb02af

I achieve the discrete sampling by simply casting the parameter to `int` when calculating the likelihood. The results do look sensible, but I am unsure whether I'm introducing a bias of some sort. I imagine that rounding off a variable prior to likelihood computation is equivalent of having a stepwise likelihood and I can't see anything wrong with that (apart from it not being continuously differentiable which makes optimization difficult/impossible).

My ultimate goal would be to perform model selection as described by @fonnesbeck in http://stronginference.com/bayes-factors-pymc.html

**Comment by ipashchenko** [comment]
Hi Lars!

Consider direct calculation of evidences for model selection using ``emcee.PTSampler``. Here's a [gist] (https://gist.github.com/ipashchenko/26fc6024dfaf54f2f5f3) that does exactly this (it also checks the correctness of evidence estimation - see PR #131 and info for Parallel Tempering in ``emcee`` docs). Using the same priors the results are identical with mixture modelling in ``pymc`` (i got Bayes Factor of geometrical to Poisson model ~ 13.3, while mixture modelling gave ~ 13.7:) 
Nevertheless it's strange that @fonnesbeck used uniform prior for ``lambda`` and the same (via ``1. / (1. + lambda)`` deterministic transformation) for ``p``. It gives low probability to any ``p > 0.01`` and could induce autocorrelations and slow mixing (i suppose). With uninformative ``beta(1, 1)`` prior on ``p`` Bayes Factor is ~ 24.

Concerning your hack to use discrete parameters in ``emcee``: i checked it in this [gist] (https://gist.github.com/ipashchenko/58ce12b24f1225525c0e) where i’ve implemented calculation of marginalized posterior density of number of trials ``n``. Of course, the same priors on ``p`` and ``n`` were used both for ``emcee`` sampling and numerical calculation. Results for ``n`` looks good but for ``p`` something strange is happening. I think that posterior for ``p`` should be more smooth. So let’s wait for comments from experts:)

P.S. By the way, prior for ``p`` in your gist is ``beta(0.5, 0.5)`` - it is very informative and puts most probability near 0 and 1. So i used ``beta(1, 1)`` prior in both calculations in my gist.

**Comment by dfm** [comment]
This method for sampling with discrete parameters is absolutely correct - sorry that I never responded. It might not perform well with emcee in all cases, but I don't have any other suggestions and there isn't anything fundamentally wrong with it.

**Comment by concatenize** [comment]
Hi @dfm , I recently ran across a very similar question on the stats SE. However, I hadn't seen this thread, and I answered that rounding is not guaranteed to work. I still don't understand why it works, so would you be willing to post your own answer on that thread explaining how this sampling-with-rounding strategy actually works?  Here is the thread. Thanks!

https://stats.stackexchange.com/questions/360076/discrete-and-continuos-parameters-in-mcmc-sampler#360093

**Comment by ekernf01** [comment]
Hi @dfm , I recently ran across a very similar question on the stats SE. However, I hadn't seen this thread, and I answered that rounding is not guaranteed to work. I still don't understand why it works, so would you be willing to post your own answer on that thread explaining how this sampling-with-rounding strategy actually works?  Here is the thread. Thanks!

https://stats.stackexchange.com/questions/360076/discrete-and-continuos-parameters-in-mcmc-sampler#360093

**Comment by dfm** [comment]
The way to think about this is that since you can sample from a uniform density (e.g. Uniform(0, 1)), you can also sample from a *mixture* of uniforms like:

```
p(x) = { p1,  if 0 <= x < 1
         p2,  if 1 <= x < 2
         0,  otherwise
```

When you have a discrete parameter and you round when evaluating your probability function, that is equivalent to sampling that density - nothing about the *proposal* is changing, the sampler still lives in a continuous space!

**Comment by Gabriel-p** [comment]
This is how I visualize the "pushing" of the sampled parameter values towards a "valid" value for a discrete parameter with values (1, 2, 3, 4):

![figure_1](https://user-images.githubusercontent.com/6054951/43535463-b7ec5c28-957f-11e8-9575-ed475000923b.png)

The issue with this approach is, as Eric mentioned, that the "stretch move" should be adjusted to avoid "pushing back" the sampled values to the discrete value over and over again. Is this correct?

**Comment by davidwhogg** [comment]
I agree with everything that's been said here. My only comment is that emcee fundamentally assumes that the parameter is a *vector* in a vector space, and obeys vector operations (like add and subtract). So this method is okay! Cyclical variables like angles are harder...

**Comment by ekernf01** [comment]
I think I understand now -- for the next proposal, there's a key conceptual difference between using the rounded values and using the non-rounded values. The rounded values should only be used in the likelihood evalution. The non-rounded values must be retained to perform the next step in the chain.

**Comment by dfm** [comment]
Exactly! I see the misunderstanding now. Glad to get it sorted.

**Comment by yoavram** [comment]
Hi @dfm, quick question -- there's no advantage to rounding vs flooring the value, right?

**Comment by dfm** [comment]
@yoavram: That's right, but that will change what your bounds mean. For example, if you want a binary variable, you should set the bounds as `-0.5 < theta < 1.5` whereas, if you're flooring, you should use `0 < theta < 2`. This doesn't matter so much for binary, but if you have more classes, it'll matter more!
