### ISSUE TITLE
MPIPool crashes when not in loadbalance mode due to MPI buffering failure

### ISSUE THREAD

**Issue by johnbachman** [dfm/emcee#151]
Hi, thanks for this great tool.

We've been running emcee using MPI and have occasionally found that the program crashes with the following error:

```
  File ".../emcee/ptsampler.py", line 259, in sample
    results = list(self.pool.map(fn, p.reshape((-1, self.dim))))
  File ".../emcee/mpi_pool.py", line 185, in map
    result = self.comm.recv(source=worker, tag=i)
  File "Comm.pyx", line 816, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:66815)
  File "pickled.pxi", line 248, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:28013)
  File "pickled.pxi", line 109, in mpi4py.MPI._p_Pickle.load (src/mpi4py.MPI.c:26549)
EOFError
```

This would occur when running PTSampler with a large number of temperatures (50) and walkers (400; so 20,000 calls to the likelihood/prior functions per step). After googling for the error message, we found a discussion on the mpi4py mailing list in which another emcee user had encountered exactly this same problem:

https://groups.google.com/forum/#!msg/mpi4py/OJG5eZ2f-Pg/EnhN06Ozg2oJ

If you read the discussion, it turns out that the problem is that when not using loadbalancing, the default strategy is to send out ALL of the tasks to the workers asynchronously and then wait for them to respond. This relies on MPI's own buffering to handle the build up of any messages. When the number of tasks is much greater than the number of workers, MPI is more likely to drop messages and cause this approach to fail. This was consistent with our experience: when running our job on 40 cores we did not get the error, whereas when running them on 12 cores we got it every time.

Using the back-of-the-envelope implementation given by Lisandro Dalcin in the thread above fixed the problem (though, as we discovered, it introduced a substantial performance penalty--since it does not store the PTLikePrior object locally on each of the workers, each MCMC step involved pickling our functions, with args, 20,000 times!). After we understood the issue, **we switched emcee to loadbalance mode, which also fixed the problem.**

It seems that there are three possible ways to address this:
1. Remove the non-loadbalance mode from MPIPool entirely.
2. Leave the non-loadbalanced code unchanged in MPIPool, while documenting this issue, and potentially making the loadbalanced code the default.
3. Modify the non-loadbalanced code to do the following:
   - Send (synchronously or asynchronously) only as many tasks as there are workers.
   - Do a waitall until all workers are finished.
   - Repeat above until all tasks are completed.

Option 3, revising the non-loadbalanced mode, would appear to be very inefficient relative to the loadbalanced mode, since it makes each round of execution wait for the slowest worker. I'm not sure I understand the advantage of the nonloadbalanced mode. If there is one, perhaps we go with option 2, allowing this mode to be "use at your own risk"? If there are no substantial advantages, I would suggest just eliminating this approach entirely and making the loadbalanced version the default (option 1).

**Comment by dfm** [comment]
The next version of emcee won't include an MPIPool (partly because of this unresolved issue). We're recommending that users switch to https://github.com/adrn/schwimmbad instead.
