### ISSUE TITLE
Blobs compatible with PTsampler?

### ISSUE THREAD

**Issue by hbrooks** [dfm/emcee#159]
Hi all, thanks for making a great code!

I was wondering if blobs are currently supported with the PTsampler?  When using them just like the EnsembleSampler, a ValueError occurs {   line 262 of ptsampler.py, in my version the line reads: logls = np.array([r[0] for r in results]).reshape((self.ntemps, self.nwalkers))   }

Am I missing something?

**Comment by mgennaro** [comment]
Hi,
yep, thanks indeed.
I see someone else had my same issue, and I am trying to revive this conversation.

After using the affine invariant sampler for a while, I have now a problem where parallel tempering may work better. However when I tried to run your PTsampler implementation, I noticed a similar issue with the blobs.
The simple solution was to rewrite my likelihood function to return only the likelihood value, and no longer the complementary info that was stored in blobs with the affine invariant sampler.
Any updates on this? I would love to have the same capability of getting the blobs in the PTsampler.
Thanks a lot,
Mario
