### ISSUE TITLE
Progress bar while sampling

### ISSUE THREAD

**Issue by tomevans** [dfm/emcee#163]
Is it possible to display a progress bar while sampling, to show what fraction of the total steps have been taken as a function of time? e.g. pymc has a nice routine for doing this.

**Comment by ipashchenko** [comment]
Hi!
Please, see PR #62 concerning progress bar addition and ``emcee`` author's  https://github.com/dfm/emcee/issues/133#issuecomment-57087428 concerning difference between ``emcee`` and ``pymc``.

**Comment by tomevans** [comment]
Thanks for the reply, Ilya. If I understand correctly then, it should be possible to wrap a progress bar routine *around* a run_mcmc() call? i.e. without having to incorporate a progress bar into the emcee code itself... If anyone has a snippet of code for doing this, I'd appreciate seeing it, as I couldn't work it out and didn't see it in the docs.

**Comment by dfm** [comment]
You can follow a pattern [like this](http://dan.iel.fm/emcee/current/user/advanced/#incrementally-saving-progress). For the simplest progress bar, this would look something like:

```
nsteps = 5000
for i, (pos, lnp, state) in enumerate(sampler.sample(p0, iterations=nsteps)):
    if (i+1) % 100 == 0:
        print("{0:.1f}%".format(float(i) / nsteps))
```

In practice you could use something like the [progressbar](https://pypi.python.org/pypi/progressbar) module but it will look very much like this example.

I'd be happy to add an example to the docs if someone submitted it ;-)

**Comment by willvousden** [comment]
I've used [clint](https://github.com/kennethreitz/clint) for this in the past.  I'll hack together an example.

**Comment by ipashchenko** [comment]
Hi, Will!
Could you please add Dan's example implementing progress bar without third party packages (https://github.com/dfm/emcee/issues/163#issuecomment-135460483) to your PR?

**Comment by willvousden** [comment]
Sure thing.  I've replaced the clint example with Dan's example and another to illustrate how to make an actual progress bar.

**Comment by tomevans** [comment]
Thank you all - I've finally gotten around to implementing it myself, following your suggestions.

**Comment by GaelO** [comment]
Hi ! I tried looking around for a solution to my problem but didn't find any: 
I implemented a progress bar to the **Fitting a Model to Data** example. But it appears to add an _nsteps_  MCMC, and then launch a second one right behind with the _N_ steps argument from _run_mcmc_.
Here's a example of such a chain, with _nsteps = 300_, and _N=500_

![image](https://cloud.githubusercontent.com/assets/23503305/20352660/5542cd02-ac18-11e6-87c9-597e3b22a0f6.png)

with this piece of code:

```
ndim, nwalkers = 3, 100
pos = [result["x"] + 1e-4*np.random.randn(ndim) for i in range(nwalkers)]
sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=(x, y, yerr))

nsteps, width= 300, 30
for i, result in enumerate(sampler.sample(pos, iterations=nsteps)):
    n = int((width+1) * float(i) / nsteps)
    sys.stdout.write("\r[{0}{1}]".format('#' * n, ' ' * (width - n)))
sys.stdout.write("\n")

sampler.run_mcmc(pos, 500, rstate0=np.random.get_state())

```

I do not understand how this is explainable, and I'm sure this is silly.

Any idea what I did wrong ?
