### ISSUE TITLE
How does parallelisation occur?

### ISSUE THREAD

**Issue by andyfaff** [dfm/emcee#165]
I was wondering how the parallelisation was implemented inside emcee.   For a computer with `N` cores does the parallelisation split the `M` walkers into `M / N` calculations to be distributed to each processor, on a single step?
-OR-
Does the parallelisation distribute across steps as well?

**Comment by dstndstn** [comment]
The former; it uses python's multiprocessing.Pool.map.  It's not possible to take steps in parallel, at least not if you want to walk (try it using your legs). ;)
Here's the map call:
https://github.com/dfm/emcee/blob/master/emcee/ensemble.py#L382
