### ISSUE TITLE
Autocorrelation Times

### ISSUE THREAD

**Issue by aimalz** [dfm/emcee#171]
When the thinning factor of sampler.run_mcmc() is greater than the window size of get_autocorr_time(), nonsensical autocorrelation times < 1 are produced.  Perhaps an error message is in order for when users specify such a condition?  (Or there may be a bug in the autocorrelation time function. . .)

**Comment by dfm** [comment]
Can you give the minimal example that reproduces this result? Not using your code... give a test function.

**Comment by davidwhogg** [comment]
Alex -- can you make a few-line gist that does this?  If you can't, then I think the bug might be elsewhere.

**Comment by aimalz** [comment]
Sorry for taking so long -- my problem is that I'm not exactly sure how.  I don't think the issue is specific to one set of data because it happens for every instantiation satisfying the conditions I mentioned, but a short piece of code that generates the error would still need to include the initialization of the sampler.

**Comment by davidwhogg** [comment]
Just make the shortest piece of code you can that repeats the bug.  This is top priority, because we absolutely cannot have emcee be wrong, mathematically.

**Comment by tobeplugged** [comment]
I've just stumbled over the same problem. It seems that this can happen if the number of iterations is in the same order of magnitude than the window width used for the acf.

For example:
    emcee.autocorr.integrated_time(np.random.randn(50), window=50)

This does not always produce nonsensical values but sometimes. I hope this helps.

**Comment by dfm** [comment]
Yeah. You should check out: http://www.stat.unc.edu/faculty/cji/Sokal.pdf (linked from the docs) for advice about setting the window; you can't use a window that's the same length as your chain! I've also implemented a more automated method on the GitHub master branch.

**Comment by tobeplugged** [comment]
Thanks for the reference, I've missed that. But even with longer samples (i.e. 1000) it happens quite often, that the autocorrelation time is smaller than 1.0, is that expected?

**Comment by dfm** [comment]
Even when you set the window correctly?

**Comment by tobeplugged** [comment]
Yes it does, see this example:

    np.random.seed(1234)
    s = np.array([emcee.autocorr.integrated_time(np.random.randn(1000), window=50) for _ in range(1000)])
    print np.mean(s < 1.0), np.mean(s < 0.0)
    
    0.632 0.002

1000 samples should be enough for a window size of 50 I think

**Comment by dfm** [comment]
Not quite. It's just an estimator so it does have some empirical distribution. Compare for example the distribution of estimated taus for 1000 samples and 10,000 samples (blue vs. green histograms below) to get a sense of the precision. 

![acor](https://cloud.githubusercontent.com/assets/350282/11149212/3c974c46-8a19-11e5-9d05-907ddac6a580.png)

**Comment by davidwhogg** [comment]
I still don't understand how tau can be less than 1.  Is it because the cross-correlations go negative fast?  I am just confused.

**Comment by dfm** [comment]
Yeah... and it has to do with the window choice. If you follow the directions from Sokal's directions for setting the window size (that I link to above and in the docs), you get this (for 1000 samples): 

![acor2](https://cloud.githubusercontent.com/assets/350282/11165734/1c043582-8b10-11e5-916d-d1d9ccc95961.png)

An implementation of Sokal's method is here: https://github.com/dfm/emcee3/blob/master/emcee3/autocorr.py

**Comment by davidwhogg** [comment]
Is it *possible* for an MCMC chain to show negative correlations on short timescales?  If not, won't we have a better estimator if we don't permit any negative numbers to enter the sum?
