### ISSUE TITLE
Include Hamiltonian Monte Carlo on emcee

### ISSUE THREAD

**Issue by poveda-ruiz** [dfm/emcee#177]
It would be possible to include a Hamiltonian Monte Carlo sampler for emcee? I know that we could write it, but the real question is if you consider that it could be included on emcee or if it should be on another module. Thanks!

Pd: If the answer is yes, I would be interested in doing it

**Comment by inti** [comment]
Not the right person to answer the question but did you see https://github.com/mcleonard/sampyl and the autograd package it uses to calculate derivatives for HMC?

**Comment by poveda-ruiz** [comment]
That's sad, I was implementing the same idea :(

**Comment by dfm** [comment]
@poveda-ruiz I'm also working on a version of emcee that includes HMC etc. for the next big release: https://github.com/dfm/emcee3

**Comment by poveda-ruiz** [comment]
I'll be more than happy to collaborate
