### ISSUE TITLE
emcee documentation - Incrementally saving progress error

### ISSUE THREAD

**Issue by TimothyADavis** [dfm/emcee#181]
Hi,

In the current documentation the suggestion for saving the progress of a chain as it goes does not work (at least on my system- Python 3.5.1, numpy 1.10.4). It raises an error: 

> TypeError: sequence item 0: expected str instance, numpy.float64 found

I suggest a change of:
`f.write("{0:4d} {1:s}\n".format(k, " ".join(position[k])))`

to

`f.write("{0:4d} {1:s}\n".format(k, " ".join(map(str, position[k]))))`

which then works as intended for me.

**Comment by dfm** [comment]
This has been fixed finally for the next release. Took long enough :-\
