### ISSUE TITLE
How to monitor progress and stop mcmc if certain variance in the parameter is reached

### ISSUE THREAD

**Issue by abhisheksubu92** [dfm/emcee#183]
While running  mcmc it is a practice to check the convergence by plotting the auto correlation time or using the Gelman-Rubin metric. How can one check these in emcee? Thanking in advance

**Comment by dfm** [comment]
You can use [this pattern](http://dan.iel.fm/emcee/current/user/advanced/#incrementally-saving-progress) and check any starts you want at any interval. Be careful with GR because the walkers in the ensemble are not independent.

**Comment by abhisheksubu92** [comment]
cool thanks a lot for the timely reply

**Comment by sbruzzone** [comment]
Just a very silly question. I'd like to incrementally save the progress of the sampler and I was looking
at the solution on Advanced Patterns. I'm a bit confused about that example, as it's not clear to me if the chain is stored every 500 steps or up to that number. Thank you!

**Comment by dfm** [comment]
As I said, the walkers are not independent. The derivation of the GR statistic requires parallel independent chains. You're welcome to run multiple instances of the ensemble starting from initializations randomly selected in your prior but you can't use the GR statistic within the ensemble.

**Comment by kayhangultekin** [comment]
Is what was written at [http://joergdietrich.github.io/emcee-convergence.html](http://joergdietrich.github.io/emcee-convergence.html) reasonable?

**Comment by dfm** [comment]
That is not formally correct because, as I said, the walkers are not independent (despite what is said in the blog post). It might work to diagnose some cases if you're lucky, but it definitely isn't as robust as in the independent case. I recommend monitoring the autocorrelation time and setting a target number of independent samples.

**Comment by davidwhogg** [comment]
...with the caveat that the autocorrelation time estimate is usually poor until you have run for many autocorrelation times. Note chicken-and-egg issue.

**Comment by dfm** [comment]
FWIW: the default settings for the algorithm here are fairly robust to that
in many cases - only confident estimates are returned - but there are
always some situations that none of these heuristics catch. I definitely
wouldn't say that the GR statistic is more robust.

**Comment by kayhangultekin** [comment]
Thanks. That is quite helpful.
