### ISSUE TITLE
Using emcee with a shared multiprocessing array 

### ISSUE THREAD

**Issue by catherinezucker** [dfm/emcee#184]
Is there any way to force emcee to work on a shared multiprocessing array without significantly modifying any of the internal code? I'm running into the issue of trying to parallelize a PTSampler process that accepts a 25+ GB array as a likelihood argument. This array is read-only and never needs to be modified by any of the child processes. I understand that within the python multiprocessing module the Pipe pickles an object it receives and passes those bytes to the partner process which then unpickles it. However, a 25+ GB array is too large to be passed (and even if it was, is a huge performance bottleneck for the code), so I get the following error: 

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
error                                     Traceback (most recent call last)
<ipython-input-2-5341c9a8e13c> in <module>()
      1 # run the sampler and time how long it takes
----> 2 get_ipython().magic('time sampler.run_mcmc(starting_positions, nsteps)')
      3 print('Sampler Done')

/n/home12/czucker/envs/PYTHON3/lib/python3.4/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2161         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2162         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2163         return self.run_line_magic(magic_name, magic_arg_s)
   2164 
   2165     #-------------------------------------------------------------------------

/n/home12/czucker/envs/PYTHON3/lib/python3.4/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2082                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2083             with self.builtin_trap:
-> 2084                 result = fn(_args,_*kwargs)
   2085             return result
   2086 

<decorator-gen-60> in time(self, line, cell, local_ns)

/n/home12/czucker/envs/PYTHON3/lib/python3.4/site-packages/IPython/core/magic.py in <lambda>(f, _a, *_k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, _a, *_k: f(_a, *_k)
    194 
    195         if callable(arg):

/n/home12/czucker/envs/PYTHON3/lib/python3.4/site-packages/IPython/core/magics/execution.py in time(self, line, cell, local_ns)
   1171         if mode=='eval':
   1172             st = clock2()
-> 1173             out = eval(code, glob, local_ns)
   1174             end = clock2()
   1175         else:

<timed eval> in <module>()

/n/home12/czucker/envs/PYTHON3/lib/python3.4/site-packages/emcee/sampler.py in run_mcmc(self, pos0, N, rstate0, lnprob0, *_kwargs)
    155         """
    156         for results in self.sample(pos0, lnprob0, rstate0, iterations=N,
--> 157                                    *_kwargs):
    158             pass
    159         return results

/n/home12/czucker/envs/PYTHON3/lib/python3.4/site-packages/emcee/ptsampler.py in sample(self, p0, lnprob0, lnlike0, iterations, thin, storechain)
    257                 results = list(map(fn, p.reshape((-1, self.dim))))
    258             else:
--> 259                 results = list(self.pool.map(fn, p.reshape((-1, self.dim))))
    260 
    261             logls = np.array([r[0] for r in results]).reshape((self.ntemps,

/n/home12/czucker/envs/PYTHON3/lib/python3.4/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    258         in a list that is returned.
    259         '''
--> 260         return self._map_async(func, iterable, mapstar, chunksize).get()
    261 
    262     def starmap(self, func, iterable, chunksize=None):

/n/home12/czucker/envs/PYTHON3/lib/python3.4/multiprocessing/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

/n/home12/czucker/envs/PYTHON3/lib/python3.4/multiprocessing/pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    383                         break
    384                     try:
--> 385                         put(task)
    386                     except Exception as e:
    387                         job, ind = task[:2]

/n/home12/czucker/envs/PYTHON3/lib/python3.4/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

/n/home12/czucker/envs/PYTHON3/lib/python3.4/multiprocessing/connection.py in _send_bytes(self, buf)
    401        # For wire compatibility with 3.2 and lower
--> 402         header = struct.pack("!i", n)
    403         if n > 16384:
    404            # The payload is large so Nagle's algorithm won't be triggered

error: 'i' format requires -2147483648 <= number <= 2147483647`
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

My solution was to make a shared multiprocessing array for the 25+ GB array (following [this example](https://books.google.com/books?id=bIZaBAAAQBAJ&pg=PA253&lpg=PA253&dq=pool.map+shared+multiprocessing+array&source=bl&ots=ehckbxcy2w&sig=lq3PBr9oqH_44jPqurRjlqVGL5c&hl=en&sa=X&ved=0ahUKEwjExfjq_bfNAhUBWj4KHXz_Bq84ChDoAQg8MAU#v=onepage&q=pool.map%20shared%20multiprocessing%20array&f=false)) before sending it to PTSampler as a likelihood argument. I'm just using the threads=nthreads argument under PTSampler to indicate I want it to multiprocess. However, I'm stuck with the same error as above: it keeps trying to pickle this giant array despite supposedly passing it as a shared memory array. Do you have any ideas how to easily resolve this issue using the existing emcee framework? Any help would be greatly appreciated!

**Comment by manodeep** [comment]
Does the array correspond to a file on disk? If so, it should be possible to create a shared `mmap` created by the parent process, and then recreate that same mapping within the `lnprob` routine. Since multi-processing works only on the same node, this has the added benefit of better caching. This solution will however require manual slicing for the array. 

The `mmap` doc for python3.4 is here: https://docs.python.org/3.4/library/mmap.html
For your case, you will want to use the `PROT_READ` (assuming Unix-like OS.) 

Hope this helps. If not, could you post a short snippet of code that shows the issue.
