### ISSUE TITLE
VisibleDeprecationWarnings and Errors in downstream projects because PyPi release is old

### ISSUE THREAD

**Issue by andyfaff** [dfm/emcee#185]
Changes to recent versions of numpy make creating an array with non-ints a `TypeError`, e.g. `np.zeros(num)` doesn't work if num is not an int. Issues relating to these numpy changes were fixed in `ptsampler.py` in August 2014 (https://github.com/dfm/emcee/commit/a4da655815a30011ec189d4d2f93a73d5b4fff98) and also in #175. However, these fixes are not in the current release version on PyPi, which dates from May 2014. This means that one cannot use `PTSampler` with current numpy and the current PyPi release of emcee.
This is also causing downstream issues in a project which uses emcee, https://github.com/lmfit/lmfit-py/issues/350. Is there a timeline for the next release of emcee on PyPi because at the moment significant functionality doesn't work and this issue is having knockon effects downstream?

**Comment by dfm** [comment]
Done. I just uploaded version 2.2.0 to PyPI and this should include the fix. It really has been too long!

**Comment by andyfaff** [comment]
Thanks @dfm, that helps a lot.
