### ISSUE TITLE
Function autocorr.integrated_time() missing "window" keyword argument

### ISSUE THREAD

**Issue by turnerm** [dfm/emcee#187]
It looks like when the autocorr.integrated_time() function was updated recently, the "window" keyword was removed. However, this function is still called with "window=50" as an argument in both ensemble.py and mh.py. 

The keyword error was triggered for me using the example script quickstart.py.

**Comment by dfm** [comment]
This should be fixed in v2.2.1 that was just pushed. Sorry about that!
