### ISSUE TITLE
SLURM srun error

### ISSUE THREAD

**Issue by vvinuv** [dfm/emcee#190]
Hi Admin
I was trying to run emcee on a cluster. However, I found a few errors when I run the python code with srun (the SLURM command). My slurm script is following
# !/bin/bash
# SBATCH -p debug
# SBATCH -N 1
# SBATCH -n 32
# SBATCH -t 00:30:00
# SBATCH -o debug_cori.out
# SBATCH -e debug_cori.err

module load gsl
srun -n 32 /global/project/projectdirs/des/vinu/software/anaconda_Jul12_2016/bin/python ./test_cori_debug.py

The python code test_cori_debug.py is following

import sys
import numpy as np
import emcee
import time
from emcee.utils import MPIPool

variances=np.array([1,1,1,1]) # true variances
means=np.array([0,0,0,0]) # true means
labels=['a','b','c','d'] # parameter labels

def lnprior(x):
    # this is the prior on the log-likelihood lnL set to -infinity for forbidden regions
    if ( -10<x[0]<10 and -10<x[1] < 10 and -10<x[2]<10 and -10<x[3]<10 ):
        return 0.0
    return -np.inf

def lnprob(x):
    if not np.isfinite( lnprior(x) ):
        return -np.inf
    return -0.5 \* np.sum((x-means)*_2/variances *_ 2)
# number of dimensions and walkers:

ndim = 4
nwalkers = 8
chain_length = 1
nthreads = 1

# the starting point for each walker: each walker should have a different(!) starting point inside the prior, close to the expected max. likelihood region
p0 = np.array([5 -1 + 2*np.random.rand(ndim) for i in range(nwalkers)])

# Initialize the MPI-based pool used for parallelization.
pool = MPIPool(loadbalance=True)

if not pool.is_master():
    # Wait for instructions from the master process.
    pool.wait()
    sys.exit(0)
sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, pool=pool)
fsample = 'samples_test_cori_debug.txt'
f = open(fsample, 'w')
f.close()
steps = 1
for result in sampler.sample(p0, iterations=chain_length, storechain=False):
    position = result[0]
    with open(fsample,'a') as f_handle:
        np.savetxt(f_handle,position)
    print steps,'done at',time.strftime("%Y%m%d-%H%M%S")
    steps+= 1
pool.close()

The error is

Traceback (most recent call last):
  File "./test_cori_debug.py", line 45, in <module>
    pool = MPIPool(loadbalance=True)
  File "build/bdist.linux-x86_64/egg/emcee/mpi_pool.py", line 66, in **init**
ValueError: Tried to create an MPI pool, but there was only one MPI process available. Need at least two.
....etc. 

srun: error: nid00027: tasks 9,15: Exited with exit code 1
srun: Terminating job step 2785683.0
slurmstepd: error: **\* STEP 2785683.0 ON nid00027 CANCELLED AT 2016-07-29T08:43:20 

I think the error tells that there is only one MPI process available. Do you know why this error happens? Is it possible to fix this error?
Thanks
Vinu

**Comment by dfm** [comment]
Sounds like it's probably something like this: http://stackoverflow.com/a/31959110

Try googling a bit – the MPIPool works on clusters but sometimes the specific MPI choice can be finicky.

**Comment by simongibbons** [comment]
I've run emcee on Cori before.

The issue is that the python interpreter that you are run needs to be linked with one of the slum libraries so that it knows how many processes to start.

The mpi4py module on Cori will have created one for you, the executable is called python-mpi.

**Comment by manodeep** [comment]
I had a similar error (job would crash on >~100 cores) on Stampede that was solved by using the correct `python-mpi` from `mpi4py`. Here's what my final run step (after all slurm commands) looks like:
`ibrun path/to/mpi4py/bin/python-mpi emcee_script.py <command-line args>`

**Comment by vvinuv** [comment]
Thank you for the prompt replies. I have contacted with the Cori admin and asked him to how to compile the mpi4py module on Cori. After compilation I could run the emcee code. On Cori the following commands need to be run to work with emcee 

1. Recommended to install Anaconda python in your account. Otherwise 'module load python'
2. wget https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-2.0.0.tar.gz
3. module swap PrgEnv-intel PrgEnv-gnu
4. tar zxvf mpi4py-2.0.0.tar.gz
5. cd mpi4py-2.0.0
6. python setup.py build --mpicc=$(which cc)
7. python setup.py build_exe --mpicc="$(which cc) -dynamic"
8. python setup.py install
9. Install emcee
