### ISSUE TITLE
AutocorrError, 'The chain is too short to reliably estimate the autocorrelation time'

### ISSUE THREAD

**Issue by ReddTea** [dfm/emcee#195]
I've been using emcee without any problems for a while. Recently I tried running my program in Windows10, but I get an error with the autocorr (that I didn't get before).
Using the quickstart.py example I get the same problem but I can't figure out whats wrong whatsoever.
I hope you can help me figuring out whats wrong . This is the log I get running quickstart.py :

``` python
In [1]: run quickstart.py
Mean acceptance fraction: 0.191032
---------------------------------------------------------------------------
AutocorrError                             Traceback (most recent call last)
C:\Users\anibal\Documents\GitHub\emcee\examples\quickstart.py in <module>()
     58 # Estimate the integrated autocorrelation time for the time series in each
     59 # parameter.
---> 60 print("Autocorrelation time:", sampler.get_autocorr_time())
     61
     62 # Finally, you can plot the projected histograms of the samples using

C:\Users\anibal\Anaconda2\lib\site-packages\emcee-2.2.1-py2.7.egg\emcee\ensemble.pyc in get_autocorr_time(self, low, high, step, c, fast)
    501         return autocorr.integrated_time(np.mean(self.chain, axis=0), axis=0,
    502                                         low=low, high=high, step=step, c=c,
--> 503                                         fast=fast)
    504
    505

C:\Users\anibal\Anaconda2\lib\site-packages\emcee-2.2.1-py2.7.egg\emcee\autocorr.pyc in integrated_time(x, low, high, step, c, full_output, axis, fast)
    116             break
    117
--> 118     raise AutocorrError("The chain is too short to reliably estimate "
    119                         "the autocorrelation time")
    120

AutocorrError: The chain is too short to reliably estimate the autocorrelation time
```

**Comment by franciscaconcha** [comment]
I am having the same problem with the quick start example, also can't figure out what's wrong

**Comment by ReddTea** [comment]
After that I tried again in Ubuntu, and the problem persists (so windows is not the problem [😂]   ). Truth is that I left it on hold. Have you tried with an older version of emcee?
________________________________
De: Francisca Concha <notifications@github.com>
Enviado: miércoles, 05 de octubre de 2016 10:19:58
Para: dfm/emcee
Cc: Pablo Aníbal Peña Rojas; Author
Asunto: Re: [dfm/emcee] AutocorrError, 'The chain is too short to reliably estimate the autocorrelation time' (#195)


I am having the same problem with the quick start example, also can't figure out what's wrong

**Comment by franciscaconcha** [comment]
Hi, I commented yesterday saying I had the exact same problem and error log on Fedora 23. However, running the example through PyCharm worked perfectly, so I removed my previous comment given it was obvious emcee was not the problem in my case. I hope you can fix it.

**Comment by duerrp** [comment]
I run into the same problem here... (Ubuntu 16.04, Python 2.7.12)

**Comment by sbruzzone** [comment]
Hi, I'm running into to same issue. Even when using PyCharm 2106 2.3 on Debian 8 amd64. The quickstart.py and the PT sample example codes report the same problem. Hard to find any response here.

**Comment by dfm** [comment]
The most recent version of emcee has a more robust autocorrelation time estimator so I reduced the dimensionality of the quickstart example and ran more steps of MCMC. This error won't be thrown for the example now and, if you're finding it with your own code, that means that your chains probably haven't converged! If you must, you can reduce the [`c` parameter](http://dan.iel.fm/emcee/current/api/#emcee.autocorr.integrated_time) to a smaller value but the estimate won't be as reliable so be careful.

**Comment by sbruzzone** [comment]
Great! I just tested it and works just fine. Thank you for fixing that and congrats for such a useful code.

**Comment by shantanu9847** [comment]
Hello, I get the same error when I do 
print sampler.acor.max() and using the same example on EMcee help page on fitting to a model data.
 I am using emcee version 2.2.1 on el capitan 

Traceback (most recent call last):
  File "testemcee.py", line 54, in <module>
    print sampler.acor.max()
  File "/usr/local/lib/python2.7/site-packages/emcee/ensemble.py", line 476, in acor
    return self.get_autocorr_time()
  File "/usr/local/lib/python2.7/site-packages/emcee/ensemble.py", line 503, in get_autocorr_time
    fast=fast)
  File "/usr/local/lib/python2.7/site-packages/emcee/autocorr.py", line 118, in integrated_time
    raise AutocorrError("The chain is too short to reliably estimate "
emcee.autocorr.AutocorrError: The chain is too short to reliably estimate the autocorrelation time

Do I understand correctly that this is not an issue  with emcee

**Comment by dfm** [comment]
Are you using the updated version of the example? The error is thrown if you don't run your chain for long enough.

**Comment by shantanu9847** [comment]
I used the same example as in http://dan.iel.fm/emcee/current/user/line/ (Is this the latest updated version?). I ran the chain for 5000 steps (whereas the above page runs it for 500 steps).
But still same error. If I am not using the latest version of the example, apologies. But let me know the correct location

**Comment by dfm** [comment]
That's a different example after all. Do the plots look similar when you run it?

I'm surprised that that one is causing problems - it's only 3D after all! I'll look at it later today.

**Comment by shantanu9847** [comment]
Yes, I forgot to mention that the plots look similar to what's on the webpage. If I use different starting guesses, though I don't get convergence to the true values. Anyhow let me know if you can replicate the error

**Comment by shantanu9847** [comment]
Hi Dan,
Were you able to reproduce the error I got ? I am getting the same error on
a different machine on a different example and hence wanted to make sure
its resolved for the example usecase.
Thanks

**Comment by Vladan1986** [comment]
Hello, I have the same error. I have increased the walkers from 1 000 to 10 000 and I still get the same error.
I am using Ubuntu 16.04

**Comment by deltasata** [comment]
Following this [https://emcee.readthedocs.io/en/stable/tutorials/line/#the-generative-probabilistic-model](url)
Got the same error "The chain is too short to reliably estimate the autocorrelation time". 

Also got the error:
1. "EnsembleSampler' object has no attribute 'get_chain" when executing `samples = sampler.get_chain()`

2. "sample() got an unexpected keyword argument 'progress'" when executing `sampler.run_mcmc(pos, 5000, progress=True)`
from the main emcee documentation page.
I am using python 2.7

Please help.
Thank you.

**Comment by dfm** [comment]
@deltasata: you need to update emcee (to >3) or follow [the old docs](https://emcee.readthedocs.io/en/v2.2.1/). Python 2.7 is no longer officially supported for emcee v3 however.
