### ISSUE TITLE
Multiprocessing issue when writing/reading files at each step

### ISSUE THREAD

**Issue by tomevans** [dfm/emcee#196]
I'm needing to use some 3rd party FORTRAN software to evaluate my log likelihood function at each step. Unfortunately, this software requires a plain text file to be written to disk which the FORTRAN software then reads and takes as input to compute the likelihood. In practice, each walker will require a separate input text file to be written at each step. I'd like to run this in multiprocessing mode (threads>1), but unfortunately it crashes. From what I can tell, there's some issue with the input files not being generated as I'd expect for each walker at the log likelihood evaluation. To illustrate the qualitative nature of the issue, I've added a simple hack of the Quickstart example from the emcee website below, followed by the error message I get when it crashes; it's the same issue I'm getting in my more specific application. Any suggestions on what I'm doing wrong, or if this sort of thing is even possible, would be much appreciated. thanks :)

######################################################
import emcee
import numpy as np
import os, time
def lnprob(x, mu, icov):
    tempfile = '{0}.in'.format( int( (1e6)*time.time() ) ) # generates unique input filename
    np.savetxt( tempfile, icov ) # write inputs to disk
    icov_reread = np.loadtxt( tempfile ) # in my application, it's actually a FORTRAN program that reads this input file
    os.remove( tempfile )
    diff = x-mu
    return -np.dot(diff,np.dot(icov_reread,diff))/2.0
ndim = 50
means = np.random.rand(ndim)
cov = 0.5 - np.random.rand(ndim ** 2).reshape((ndim, ndim))
cov = np.triu(cov)
cov += cov.T - np.diag(cov.diagonal())
cov = np.dot(cov,cov)
icov = np.linalg.inv(cov)
nwalkers = 150
p0 = np.random.rand(ndim * nwalkers).reshape((nwalkers, ndim))
sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=[means, icov], threads=4)
pos, prob, state = sampler.run_mcmc(p0, 150)
######################################################

emcee: Exception while calling your likelihood function:
  params: [ 0.00416683  0.00121443  0.09297952  0.88577573  0.19752657  0.43616513
  0.82632147  0.92474106  0.5263543   0.13451031  0.15140635  0.28707279
  0.83895138  0.13485659  0.67149602  0.0437184   0.52699409  0.30602217
  0.49810951  0.05429097  0.09616479  0.56352244  0.40038342  0.96128477
  0.96139381  0.30692886  0.66910766  0.10697474  0.66191896  0.33147187
  0.46090604  0.22815596  0.97349513  0.0471428   0.8184995   0.85949838
  0.81470446  0.95773865  0.70743459  0.19343325  0.82486592  0.85985209
  0.0808939   0.54152892  0.61528055  0.53683463  0.77863934  0.88026515
  0.97775209  0.36900002]
  args: [array([ 0.58793961,  0.92810062,  0.17459986,  0.20492939,  0.18346653,
        0.53892566,  0.57584874,  0.94185575,  0.24163453,  0.41284317,
        0.48564821,  0.67920761,  0.34323044,  0.2020662 ,  0.04917549,
        0.83358774,  0.20774804,  0.56789084,  0.21685981,  0.29940764,
        0.87879338,  0.93357872,  0.55544829,  0.11536287,  0.08379872,
        0.25626357,  0.65025791,  0.45939602,  0.00942292,  0.91788029,
        0.80075432,  0.14981844,  0.9870799 ,  0.85341932,  0.62013305,
        0.69599445,  0.3301484 ,  0.20774183,  0.10103013,  0.59141142,
        0.83804104,  0.31710734,  0.98339552,  0.56217429,  0.13204708,
        0.51717227,  0.9444871 ,  0.80968058,  0.71109077,  0.07345402]), array([[  5.8661203 ,   2.63731571,  -2.74252383, ...,   0.35754405,
          1.63243834,   0.41132016],
       [  2.63731571,   4.7774109 ,   4.78864275, ...,  -0.99615663,
          6.5050327 ,  -5.25536002],
       [ -2.74252383,   4.78864275,  34.84112813, ...,   0.42214212,
         17.77711414, -25.9003554 ],
       ..., 
       [  0.35754405,  -0.99615663,   0.42214212, ...,   2.69706443,
         -2.79463492,   0.27055001],
       [  1.63243834,   6.5050327 ,  17.77711414, ...,  -2.79463492,
         17.00835671, -15.69519896],
       [  0.41132016,  -5.25536002, -25.9003554 , ...,   0.27055001,
        -15.69519896,  21.18178664]])]
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "/home/tevans/.local/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/home/tevans/code/pacode/atmo/run/hat-p-18/EmceeMultithreadTest.py", line 12, in lnprob
    os.remove( tempfile )
OSError: [Errno 2] No such file or directory: '1474885596433220.in'

**Comment by manodeep** [comment]
I am assuming you pass the name `tempfile` into your fortran application. My guess is that there is a race condition in your code, and two threads generate the exact same filename. One thread removes the file and then the other tries to remove this non-existent file and crashes. Either way, a better approach would be to use unique filenames; easiest way might be to fix the filename **per** thread, using something like thread-id (or rank in MPI mode). 

If you want to use distinct filenames, check out [tempfile](https://docs.python.org/2/library/tempfile.html). In particular, `tempfile.NamedTemporaryFile` should suit your purpose; just set `delete=False`.

**Comment by tomevans** [comment]
Thanks! That seems to have fixed my issue :) I really appreciate your help!
