### ISSUE TITLE
MHSampler fails to sample uniform posterior likelihood

### ISSUE THREAD

**Issue by marius311** [dfm/emcee#198]
Perhaps I'm missing something but shouldn't this work? 

```python
sampler = emcee.MHSampler(eye(1), 1, lambda x,: 0 if -1<x<1 else -inf)
sampler.run_mcmc([0],100)
```

That should get me samples uniformly distributed from -1 to 1, but instead the chain never moves, i.e. 
```python
> all(sampler.chain==0)
True
```

I'm using emcee 2.2.1 and Python 3.5.2.

**Comment by dfm** [comment]
Good catch! That is a bug. Fixed on master.

**Comment by marius311** [comment]
Looks good, thanks for the quick fix!
