### ISSUE TITLE
how to define the tiny gaussian balls to start

### ISSUE THREAD

**Issue by sultanier** [dfm/emcee#201]
I have a question here: I have three parameters ranging (-1.0, 2.0), (37.0, 43.0), (0.0,1.0)
I dont know what is the right separation to use in here some exapmles show: 
pos = [result["x"] + 1e-4_np.random.randn(ndim) for i in range(nwalkers)]
and others use 
pos = [result["x"] + 1e-8_np.random.randn(ndim) for i in range(nwalkers)]

so how do I judge this? can I use anything from 1e-4 to 1e-8 or there is a way to select this parameter.

Thanks in advance

**Comment by dfm** [comment]
There's no formal reason to initialize in a Gaussian ball like this. I've just found that it works well for many problems in practice. The best initialization scheme will depend on your problem so it's worth trying out various options. The only thing to remember is that you need to be within your allowed parameter ranges.

**Comment by sultanier** [comment]
Thanks
