### ISSUE TITLE
Which Posterior to consider from PTSampler temperatures output?

### ISSUE THREAD

**Issue by sultanier** [dfm/emcee#202]
I would like to ask quick questions about PTSampler: 

1 - When using PTSampler, the ouptut chain has a shape of (ntemps, nwalkers, nsteps, ndim), so for each ntemps we have a chain of a shape (nwalkers, nsteps, ndim) which gives different posterior distribution. Which posterior that I should consider as my result? should I consider all of them such that I plot the whole sample with the shape ==  (ntemps*nwalkers*nsteps, ndim)? OR I should consider the first ntemps as its the highest temperature I believe? 

2 - Is there any need to use run_mcmc after running sampler.sample?

Thanks in advance.

**Comment by msspektor** [comment]
1 - The very first of the ntemps is your target distribution.

2 - As far as I know, run_mcmc is just a wrapper for sample. So no, no need.

**Comment by sultanier** [comment]
thanks so much :)
