### ISSUE TITLE
Parallel tempering execution 

### ISSUE THREAD

**Issue by sbruzzone** [dfm/emcee#203]
This is not an issue but rather a question regarding the parallel implementation of the parallel tempering sampler with emcee. (Sorry if this is not the place to ask this stuff)

Let me explain. I'm currently running a parallel tempered code with emcee using nthreads = 8. 
Each thread calls a code in fortran to generate my model data. In each of these calls, the code in fortran is executed on 8 threads where I'm using OMP_NUM_THREADS=8 because that's the optimum set up for that particular fortran code. In this way I'm using the 32 cores available with redundancy. 

The parallel tempering code executes just fine but after ~100 iterations(~50% of burn-in), the code starts to slow down, from the initial 7 mins for -each- iteration (20 walkers, 5 temps and 10 dimensions) down to 19 mins and growing.  What I see is that as iteration number increase, the code spends more time running on 8 threads and often on a single thread. Not surprised about the 8 threads running, that's actually fine, I'm puzzled about the single thread operations in particular. The plan is to complete 256 burn-in iterations, but my acceptance fraction is zero so far. So that's a red flag I bet.

I'm using 5 temps because I think my data is noisy and 100 = nwalkers x temps seems legit for 10 dimensions. 

I just want to know if this sort of behaviour is expected. I was planning to run close to 2000 iterations and initially it would take weeks. Now this sort of overheads I'm getting jeopardise my plans.

comments/suggestions?
thanks in advance
 Sebastian

**Comment by manodeep** [comment]
If your acceptance fraction is 0, then your starting points are probably unusual. But then again, I haven't used the `PTSampler` class.

If the runtimes are highly asymmetric, then you would get the observed scaling. Do you get the same behaviour if you increase the number of walkers by, say 10x ?

**Comment by manodeep** [comment]
From what I understand, any lower chi-squared *should* be accepted and consequently the acceptance fraction should not be 0.0. There is still something strange happening with either the sampler or the test setup. 

I will recommend writing out some log info from the fortran code, particularly, the time taken for executing *each* model. Pass at least one additional parameter into your fortran code that uniquely identifies each thread within `emcee`. If you could figure out where the code is spending time (which function/executable) when running on 1 thread at the end, then that would be very helpful.

**Comment by sbruzzone** [comment]
Thank you again manodeep for your comments. Unfortunately, I can't modify the fortran code as it was given to me as is. I tested that code separately before and I couldn't find anything wrong with it. On the other hand, I do know however when the python wrapper calls this fortran code, as it appears clearly on htop. The single thread operation involves the python wrapper doing 'something', it could be the pt sampler itself or not. I'm looking at the code again to see what's up with the wrapper I have. True, the acceptance fraction perhaps signals something wrong with my implementation. My debugging skills are minimal I guess. Best.
