### ISSUE TITLE
Necessary to have separate `logl` and `logp` functions with `PTSampler`?

### ISSUE THREAD

**Issue by andyfaff** [dfm/emcee#205]
When using `EnsembleSampler` one includes both the log-prior and log-likelihood terms into the `lnpostfn` function. However, for `PTSampler` one is supposed to supply `logl` and `logp` functions for the likelihood and prior.
Is it still reasonable to make a function that calculates the log-posterior, supply it as the `logl` positional parameter and use a `logp` function that returns 0? Are there situations when this is reasonable, and situations when it's not reasonable?

**Comment by dfm** [comment]
In practice, this will often work but you'll have to be careful about interpreting the marginalized likelihood integral that you get out because it isn't defined with improper priors.

I actually don't actually use the PTSampler much so @farr or @willvousden might have more intuitive comments.

**Comment by farr** [comment]
Pretty much what Dan said, plus a bit: You will also have to be careful about the adapting temperature scheme in some versions of the PTSampler.  It sets the highest temperature to infinity (i.e. draws from the prior), and therefore can never converge in your problem since the prior is improper.  Even if you don't use the adaptive temperature scheme, you will find that you don't see convergence at the high-temperature end to a common distribution (this is a common test employed to see if you have set Tmax large enough) since there is no such common distribution.  Are you really sure that you want to do this?  What's so bad about breaking out the prior in your problem?

**Comment by andyfaff** [comment]
Thanks for the help everyone. The context is that we use emcee within the [lmfit curvefitting](https://github.com/lmfit/lmfit-py/) project as a way of estimating probability distributions for the parameters. Each parameter can have lower and upper bounds, but there is no assumption on the distribution of the parameter within the bounds if they exist. The user provides an objective function that either returns a vector or a single float. If it returns a vector then it's assumed to be the residuals for the curvefitting problem (a. la. `scipy.optimize.leastsq`).  If a float is returned then that's taken to either be the log-posterior probability, or a chi2 value.  In any case these values can be used to calculate a log-posterior probability to supply to `EnsembleSampler`.
The trouble comes with `PTSampler`; the user doesn't provide a function to calculate the log-prior. Rather they provide something that I can use to calculate the log-posterior with (probably with un-normalised prior if there aren't upper and lower bounds), or they may have gone to the effort of supplying the actual log-posterior (in which case the log-prior term should be zero).
I could ask them to provide a log-prior function, but when you get to that stage I may as well just advise them to use `emcee` directly because the convenience factor of a curvefitting package is reaching its limit.

**Comment by farr** [comment]
Yeah, in this case I would just add your own flat prior, with bounds in the dimensions provided by the user (note that the prior for PT sampling doesn't have to be normalised---even if you are interested in the normalised evidence) and no bounds elsewhere, and hope that the fitting goes well.
