### ISSUE TITLE
Proposal covariance matrix in MH sampler

### ISSUE THREAD

**Issue by snaqvi1990** [dfm/emcee#207]
For various reasons I'm using the Metropolis-Hastings sampler in emcee. I'm passing it a dict of (many) parameters, and also have to pass it a covariance matrix for the proposal distribution, which presumably must be some kind of matrix/array structure. How would the sampler match up the entries of the matrix (which aren't labeled) with the strings of the parameter dict keys? Is it just in the order of the dict.keys()?

**Comment by dfm** [comment]
I'm not sure what you mean by "passing it a dict of parameters". Can you provide a code snippet? The only interface is through numpy arrays.

**Comment by snaqvi1990** [comment]
Ah ok, maybe that's the issue then. The likelihood proportion of my posterior:

    def lnlike(theta_dict,gene_go_bdict,score_dict):
        #go_wdict, sigma, delta, ymean = theta_init
        sigma = theta_dict['sigma']
        delta = theta_dict['delta']
        ymean = theta_dict['ymean']
        ngene_sum = 0
        for gene in score_dict:
            bgo_sum = 0
            for bgo in gene_go_bdict[gene]:
                bgo_sum = bgo_sum + theta_dict[bgo]
            ngene_sum = ngene_sum + math.pow((score_dict[gene] - ymean - bgo_sum),2)
        llike = (len(score_dict.keys())/2) * np.log(sigma)-(1/2 * sigma) * ngene_sum
        return(llike)

    def lnprob(theta_dict,allterm_dag,gene_go_bdict,score_dict):
        lp = lnprior(theta_dict,allterm_dag)
        if not np.isfinite(lp):
            return -np.inf
        return lp + lnlike(theta_dict,gene_go_bdict,score_dict)


theta_dict would be the "dict of parameters here"

**Comment by dfm** [comment]
And then how do you initialize the walkers? I'm surprised that this works at all.
