### ISSUE TITLE
Problem with multithreading on Windows

### ISSUE THREAD

**Issue by kevinea42** [dfm/emcee#216]
I'm having an issue getting multithreading to work on my Windows 10 machine. Setting the "threads = x" parameter in the Ensemble Sampler causes a problem if x >1.  The system seems to spawn new python.exe processes, but they just sit idle. This problem does not occur on my Mac OSX laptop however.  I'm using Anaconda and a Jupyter notebook, running Python 2.7.0 and using Emcee 2.2.1. Any ideas for troubleshooting this? Please forgive me if this is not an appropriate place to post this. Thanks.

**Comment by dfm** [comment]
This is _probably_ not an emcee problem because it just calls the [multiprocessing module](https://docs.python.org/2/library/multiprocessing.html) in the Python standard library. Can you demonstrate that the problem is not caused by that by making sure that some simple examples from those docs work properly on your machine?

**Comment by kevinea42** [comment]
Thanks for responding. I gather that multiprocessing does not work well in interactive modes such as the Jupyter notebook, so I have been trying everything in the console now. I can get simple examples like this to work in the console:
```
from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    p = Pool(5)
    print(p.map(f, [1, 2, 3]))
```
The console give this output:
```
[1, 4, 9]
```
Now, I try this code to test emcee:
```
def main():
	
	import numpy as np
	import emcee

	def lnprob(x, ivar):
    		return -0.5 * np.sum(ivar * x ** 2)

	ndim, nwalkers = 10, 100
	ivar = 1. / np.random.rand(ndim)
	p0 = [np.random.rand(ndim) for i in range(nwalkers)]

	sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=[ivar], threads=1)

	sampler.run_mcmc(p0, 5000)
	print 'Complete.'


from multiprocessing import freeze_support

if __name__ == "__main__":
	freeze_support()	
	main()
```
I inserted the "freeze_support"  lines after reading that Windows may require them, but the result is the same with or without them.  The above code runs fine and yields "Complete." after a few seconds. However, changing to "threads=2" yields a pickling error:
```
c:\Users\Kevin>python testemcee.py
Traceback (most recent call last):
  File "testemcee.py", line 23, in <module>
    main()
  File "testemcee.py", line 15, in main
    sampler.run_mcmc(p0, 5000)
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\emcee\sampler.py", line 172, in run_mcmc
    **kwargs):
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\emcee\ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\emcee\ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\emcee\interruptible_pool.py", line 94, in map
    return r.get(self.wait_timeout)
  File "C:\Users\Kevin\Anaconda2\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

Any suggestions are appreciated. Also, if anyone can verify that emcee multithreading works for them in Windows, that would be helpful.

**Comment by dfm** [comment]
Again, not emcee. Why did you define the lnprob function within main? You
would find that if you did the same in your first example, it would fail
with the same error.

**Comment by kevinea42** [comment]
You are right. I moved the lnprob function so as not to be within main, and multithreading works. No problem with emcee. Thank you!
