### ISSUE TITLE
Walker positions converging too quickly with Ensemble Sampler

### ISSUE THREAD

**Issue by rmastand** [dfm/emcee#222]
I've set up an EnsembleSampler() with 100 walkers, 2000 iterations, and thinning by every 10th iteration. However, looking at the resulting traces, I don't think my walkers are fully exploring the parameter space; often, within the first 100 iterations, the walkers converge around what the true value of the parameter is. 

Graphs below:

True parameter values: .6 and .4
<img width="821" alt="screen shot 2017-08-02 at 10 06 41 am" src="https://user-images.githubusercontent.com/20581222/28885324-60590bd4-776a-11e7-8f94-1046dd1bfa7d.png">
True parameter values: -.2 and -.8
<img width="850" alt="screen shot 2017-08-02 at 10 06 37 am" src="https://user-images.githubusercontent.com/20581222/28885326-605fbc40-776a-11e7-90b8-2e295a138e12.png">
True parameter values: -1. and 1.
<img width="841" alt="screen shot 2017-08-02 at 10 06 33 am" src="https://user-images.githubusercontent.com/20581222/28885325-605e8794-776a-11e7-9a5c-165ad6d83eac.png">

How can I get my walkers to better explore the space?

**Comment by dfm** [comment]
emcee samples from whatever probability distribution you give it and it looks like the one that you're giving here is very narrow. Do you have reason to believe that this is wrong? There doesn't seem to be anything wrong from these plots.

**Comment by rmastand** [comment]
The prior I'm giving to both parameters is uniform between -1 and 1, and the p0 distribution is a random uniform distribution also between -1 and 1. The reason I believe this is wrong is because in the emcee tutorial, http://dan.iel.fm/emcee/current/user/line/, about 2/3 of the way down there's a graph of the walker traces, and it appears that these walkers are exploring all of the parameter space for the majority of their iterations without converging to the parameters' true values too quickly. My walkers seem to do the opposite.

**Comment by dfm** [comment]
Perhaps you should read a bit more about what MCMC does. If your likelihood
tightly constrains the parameters then it doesn't matter what your prior
is! If you increase your error bars then more of the parameter space would
be sampled because the posterior would be wider.
