### ISSUE TITLE
Wrong log-prior defined in the docs?

### ISSUE THREAD

**Issue by Gabriel-p** [dfm/emcee#232]
In the docs the log-prior is [defined as](http://dfm.io/emcee/current/user/line/#marginalization-uncertainty-estimation):

```
def lnprior(theta):
    m, b, lnf = theta
    if -5.0 < m < 0.5 and 0.0 < b < 10.0 and -10.0 < lnf < 1.0:
        return 0.0
    return -np.inf
```
This will always return either zero or -inf. This can't be right, right?

**Comment by dfm** [comment]
Your interpretation is correct and that is the right log prior. What are
you concerned about? Remember that you only need to define the objective up
to a constant...

**Comment by Gabriel-p** [comment]
Sorry, I misunderstood. This line threw me off `return lp + lnlike(theta, x, y, yerr)`, I was expecting `lp` to be something other than zero or inf.
