### ISSUE TITLE
Crash in simple example due to internal variable promotion to array...error in sampler?

### ISSUE THREAD

**Issue by mb2448** [dfm/emcee#235]
Hello,

I was playing around with a simple "teaching" example of measuring the mean value of a uniform Poisson background.  Here the uncertainties depend on the mean, unlike a Gaussian distribution.

The example invariably crashes after a few iterations in the sampler.  This is due to some kind of promotion of the sampler's internal "theta" variable into a vector, causing a size mismatch error when evaluating the log-likelihood.  I think this may have to do with using a scalar model function for "time-series" data.

I've attached the code below.  If you uncomment the two lines after the `print` statement in `lnprob`, it will drop you straight into the point before the crash.  I tried to debug it myself for a while with no luck!  Is this a bug in the sampler, or is something else going on?  Can emcee be used with simple scalar models such as these?  

Thanks in advance--I've enjoyed using emcee many years now.

```python
import numpy as np
import matplotlib.pyplot as plt
import ipdb
import emcee

def model(meanval):
    return meanval

def lnprior(theta):
    if theta > 0:
        return 0.0
    else:
        return -np.inf

def lnlike(theta, data):
    mod = model(theta)
    #ln(lambda^k e^-lambda /k!)
    #stirling's approx to the factorial
    stirling = np.sum(data*(np.log(mod)-np.log(data)-1.0)-mod)
    return stirling

def lnprob(theta, data):
    print theta
    #if np.abs(theta-72.614)<0.005:
    #    ipdb.set_trace()
    lp = lnprior(theta)
    if not np.isfinite(lp):
        return -np.inf
    else:
        return lp + lnlike(theta, data)

if __name__ == "__main__":
    np.random.seed(42)
    true_bgd = 70.5
    n_points = 50
    fake_data = np.random.poisson(true_bgd, size = n_points)

    ndim, nwalkers = 1, 200
    initguess = np.median(fake_data)
    initpos   = np.random.normal(loc = initguess, scale = 2, size = n_points)
    sampler = emcee.EnsembleSampler(nwalkers, ndim,
                                    lnprob, args = [fake_data])
    sampler.run_mcmc(initpos, 100)
```

**Comment by dfm** [comment]
Try changing the initpos line to:

```
initpos = np.random.normal(loc = initguess, scale = 2, size = (nwalkers, ndim))
```

The initial guess must have shape `(nwalkers, ndim)`... you used `n_points` there, but that's not what you were going for. Looks like we need a more informative error message!

**Comment by mb2448** [comment]
Perfect!  Thanks!
