### ISSUE TITLE
Possible bug in StretchMove.get_proposal

### ISSUE THREAD

**Issue by jmatta1** [dfm/emcee#237]
I was digging through the code when I noticed a small sign difference in published versions of the stretch move proposal algorithm and how it was implemented in StretchMove.get_proposal

Goodman and Weare and Foreman-Mackey *et al.* both state that the proposed position is:
Y = X_j + Z * (X_k - X_j), where Y is the proposed new point, Z is the random scaling factor, X_j is the position of the walker drawn from the complementary ensemble, and X_k is the position of the walker to be updated. 

However, if I am reading things right, line 33 of emcee/moves/stretch.py says: Y = X_j - Z * (X_k - X_j). The result being: rather than trying to jump from X_j directly **away** from X_k you are jumping from X_j directly **towards** X_k.

I suspect that it doesn't matter, but I thought I would bring it up just in case.

**Comment by jmatta1** [comment]
Nevermind, I just noticed that what was there **actually** read:  Y = X_j - Z * (X_j - X_k).
This is equivalent to: Y = X_j + Z * (X_k - X_j), I'm just a bit thick. Sorry to bother you.

**Comment by dfm** [comment]
No worries. Thanks for taking a close look!
