### ISSUE TITLE
In master `EnsembleSampler.sample` is only yielding every `thin` steps.

### ISSUE THREAD

**Issue by andyfaff** [dfm/emcee#238]
On [L289 in ensemble.py](https://github.com/dfm/emcee/blob/master/emcee/ensemble.py#L289) `EnsembleSampler.sample` only yields (and stores) position every `thin` steps. The previous behaviour (e.g. 93d464581aa3fdb071e035502dadc9f792cc3b66) was to yield position at *every* step and store every `thin` steps.
Is this a mistake, or on purpose?  I like the original behaviour of yielding every step, it makes it easier to follow progress with long running simulations as one knows precisely how many steps have been run. It also makes it easier to checkpoint.  For example:

```
for results in sampler.sample(pos0, 99, thin=100):
    pass
```

At the end `results` will be `None` because the number of steps never reached 100 and there are 99 wasted steps because the last position was never stored and it wasn't yielded to the user.  Even if `EnsembleSampler` doesn't store a step (because it never reached `thin`), if it returned the position at every step the user wouldn't have wasted those steps for nothing. 
With the current behaviour iteration progress is also degraded. For example, in a simulation with 500 steps and `thin=100` you only know to the nearest 1/5 how many steps you have done. Yielding every step enables fine grain counting. There are many circumstances where one wouldn't want to use a tqdm progress bar. Fine grain is important if each step takes a long time. One has to be able to predict this to request a total Wall time on a supercomputer.

The docstring in both the former and current code is ambiguous. On the one hand it says `At each iteration, this generator yields:`, indicating there is a yield every iteration. On the other hand it says `If you only want to store and yield every ``thin`` samples in the chain, set thin to an integer greater than 1.`

I propose the following:

```
thin (Optional[int]): If you only want to store every ``thin`` samples in the chain, set thin to an integer greater than 1.
```

and revert L238-245 in ensemble.py to yield every iteration. It also keeps backcompat.

I'm willing to write a PR for this.

**Comment by andyfaff** [comment]
The indenting creating this issue was performed in commit https://github.com/dfm/emcee/commit/4a390cb. The commit message was adding contributors, and doesn't give any other information as to why the change was made.

**Comment by dfm** [comment]
Thanks for them comment. This was on purpose - the old behavior had been considered a bug for a long time and it was the topic of several pull requests and issues. I'll make sure the docstring is consistent when the release comes. Thanks for the heads up! 

Your comment gave me a good idea about the interface that I'll comment on when I'm at my computer.

**Comment by llimeht** [comment]
For the sake of compatibility with existing code that was built around what `thin` has historically done, can `thin` retain its current meaning and a new parameter instead be used (`yield_period` or something, but naming things is hard)? That way, users can do all sorts of fun stuff with the chain without having to store every single step.

**Comment by dfm** [comment]
That's a good suggestion. I'll work on naming and interface to try to make something satisfying to all of us.

**Comment by andyfaff** [comment]
@willvousden can PTemcee follow any new behaviour that EnsembleSampler.sample uses please (when the final behaviour is settled)?

**Comment by dfm** [comment]
@andyfaff @llimeht I'm working on updating this syntax. For reference, if either of you have specific use cases where the current definition of thin is used, can you point me to it? I'm just having a hard time imagining why it would be used. Thanks!

**Comment by andyfaff** [comment]
Most of the issues are caused by back compatibility.  I'll recap those.

- we currently incrementally save steps to file, keeping the file the same as `EnsembleSampler.chain`. This was done by writing `pos` after `sample` had yielded, but only every `nthin` steps (we needed to keep track of the number of steps). With new emcee the sampler takes care of that. If we use the same code across both old-new versions then the new version would be thinned by N**2 rather than N.
I'd prefer to use one set of code to deal with new/old emcee versions. Perhaps that could be done by keeping track of the number of iterations. The old EnsembleSampler had an `iterations` attribute, the new one doesn't.
- we kept track of steps carried out by the number of yields from sample (providing it to a progress bar). If we don't make any changes this may be out by a factor of `nthin` depending on whether the new/old version is installed. yielding every step meant that our progress bar was updated in realtime (if a step takes 30 sec, then yielding every 10 steps means an update is only seen every 5 mins). There is a tqdm progress bar in new version. However, if one wants to provide a progress bar across the new & old versions we have to do it ourselves. A design question for you - shouldn't the progress bar be left to be implemented by the user (VISION.md)?
- by yielding every step one is able to keep track of the exact state of the sampler. With the new behaviour you can lose up to `steps % nthin` steps if the sampling is interrupted. That's probably ok if your sampling is fast and you're on a PC, or if you're on a cluster and you're doing a big job. If your sampling is not so fast and you're working interactively on a PC that is a bit more annoying. 

I suppose the first two issues can be circumvented by seeing if the EnsembleSampler has an iterations attribute. If it does, then that specifies the number of iterations. If it doesn't then `np.size(chain, -2)` (trying to accomodate PTSampler as well) can be used to see what the iterations are.

**Comment by andyfaff** [comment]
Just seen that 'new' emcee has `EnsembleSampler.iteration`, whilst the old emcee has `EnsembleSampler.iterations`.  Confusing, the two aren't the same, and they're related by a factor of `nthin`.

**Comment by andyfaff** [comment]
It's probably easier for my project in the long run to use requirements.txt (or some such) to specify emcee >=3. Then I don't have to worry about compatibility any more.
(Just as long as there is a pypi / conda-forge release).

**Comment by dfm** [comment]
Thanks for the info. I'll keep you posted. It seems like, for your use case, you could just always use `thin=1` and `store=False` to get the same behavior that you want.

`iterations` was never exposed or meant to be a public attribute so I'm not worried about supporting that long term :wink:

The old behavior of thin will be supported in the next release with a deprecation warning.

The progress bar was requested enough (and I like it enough now that tqdm exists) that I decided that it was reasonable to add it.

**Comment by andyfaff** [comment]
I did quite a lot of work on my project over the past week and I think I
can now cope with a yield every thin steps (and deal with the difference
between old and new). It was a shock to the system when I saw the change.
However if you want to keep what's currently in master it's OK with me.
BTW,  if you'd like a hand with development I'd be happy to help where I
could and if time permitted.

**Comment by willvousden** [comment]
@andyfaff Sure thing.  I'll wait a little while for the dust to settle before changing anything, though.
