### ISSUE TITLE
Progress bar doesn't seem to be working?

### ISSUE THREAD

**Issue by jacaseyclyde** [dfm/emcee#239]
As the title says, the progress bar doesn't seem to be working for me (using emcee 3.0.0.dev0). I'm primarily following the method in the monitor tutorial (aka adding `progress=True` flag), except I'm using my own data. Running directly in a python terminal, tried using both 2.7 and 3.5.

For more context, here's my implementation below. Not sure if I'm just missing something or this is a bug.

    ndim = 5
    nwalkers = 1000
    
    n_max = 10000
    priors = np.array([[0.,0.,0,.1,.5],[2 * np.pi, 2 * np.pi, 2 * np.pi, 2, .999]])
    prange = np.ndarray.tolist(priors.T)
    
    filename = 'chain.h5'
    backend = emcee.backends.HDFBackend(filename)
    backend.reset(nwalkers, ndim)

    sampler = emcee.EnsembleSampler(nwalkers, ndim, lnProb, args=[data,cov], backend=backend)

    print("Running MCMC")
    old_tau = np.inf
    for sample in sampler.sample(pos, iterations=n_max, progress=True):
        if sample.iteration % 100:
            continue
    
        #check convergence
        tau = sampler.get_autocorr_time(tol=0)
        converged = np.all(tau * 100 < sampler.iteration)
        converged &= np.all(np.abs(old_tau - tau) / tau < 0.01)
        if converged:
            break
        old_tau = tau

**Comment by jacaseyclyde** [comment]
nevermind, apparently i am just running very long iterations. closing this. not a bug

**Comment by jpdeleon** [comment]
I recommend using tqdm package.
So when I run the sampler, I use it like

from tqdm import tqdm

for pos,lnp,rstate in tqdm(sampler.sample(pos0, iterations=nsteps)):
    pass

and it will show progress bar.
It works for any for loops.

**Comment by dfm** [comment]
The dev version on the master branch uses tqdm and I think that's what he
was talking about. I agree: tqdm is awesome!

**Comment by jacaseyclyde** [comment]
Yes! Loving the tqdm implementation! Problem was definitely just long iterations, so I added in multiprocessing to help my simulation along. Really excited for this next release! Keep up the good work!
