### ISSUE TITLE
Mistake in ptsampler?

### ISSUE THREAD

**Issue by andyfaff** [dfm/emcee#243]
Take the following line:

https://github.com/dfm/emcee/blob/9ac474762f321494e09eea8ee31433dc09c24823/emcee/ptsampler.py#L6

should it be:
```
try:
    from ptemcee import PTSampler
```
?

**Comment by dfm** [comment]
Not quite... it should be

```python
from ptemcee import Sampler as PTSampler
```

fixing now. Thanks!

**Comment by dfm** [comment]
but really... this shim should probably just be totally removed!
