### ISSUE TITLE
Link for full source code for linear fit example broken

### ISSUE THREAD

**Issue by charlesll** [dfm/emcee#246]
This issue concerns the documentation of emcee. 

The example for fitting a line (http://emcee.readthedocs.io/en/stable/user/line/) contains a link to the full source code, right below the first paragraph. The link is:

https://github.com/dfm/emcee/blob/master/examples/line.py

This link is broken. It seems that the examples have been moved out of Github?

**Comment by dfm** [comment]
Yeah - the docs are a mess right now. Working on it!

You can find the source code here, for now: https://github.com/dfm/emcee/tree/67c8f79928716a0c65e1e59f96fb845600ea9c2a/examples

**Comment by charlesll** [comment]
Cool, thanks!
