### ISSUE TITLE
Quite deprecation

### ISSUE THREAD

**Issue by laszukdawid** [dfm/emcee#250]
**General information:**

- emcee version: 2.2.1
- platform: Ubuntu 16.04
- installation method (pip/conda/source/other?): conda/pip

**Problem description:**

### Expected behavior:
Loud deprecation warning on deprecated fields.

### Actual behavior:
No warning appears when executing sampler with non None "threads" argument.
https://github.com/dfm/emcee/blob/master/emcee/ensemble.py#L65
https://github.com/dfm/emcee/blob/master/emcee/utils.py

### What have you tried so far?:
Running.

### Minimal example:

Doesn't evoke warning:
```python
from emcee import EnsembleSampler
sampler = EnsembleSampler(50, 5, lambda x: 0, threads=8)

```

Does evoke warning:
```python
from emcee import EnsembleSampler
import warnings
warnings.simplefilter('always', DeprecationWarning)
sampler = EnsembleSampler(50, 5, lambda x: 0, threads=8)
```

**Comment by dfm** [comment]
Thanks. As you discovered, DeprecationWarnings are ignored by default since Python 3.2. This isn't an issue with emcee.
