### ISSUE TITLE
emcee 3.0.0.dev0: new HDFBackend feature increasingly slows down the computation

### ISSUE THREAD

**Issue by MNGuenther** [dfm/emcee#252]
**General information:**

- emcee version: 3.0.0.dev0
- platform: OSX
- installation method (pip/conda/source/other?): git clone

**Problem description:**

new HDFBackend feature increasingly slows down the computation with increasing number of performed steps

### Expected behavior:
constistent iterations-per-second rates throughout

### Actual behavior:
after running a few thousand steps, i.e. with increasing filesize of the '.h5' file, the computation speed increasingly slows down. Likely because it generates a lot of overhead to open the .h5 file and write into it.

### What have you tried so far?:
bypass the issue by running emcee in chunks, and saving .h5 files in small chunks of e.g. 1000 steps. However, this somewhat means loosing the simplicity/functionality of the whole backend feature, especially when reading in and evaluating all the individual .h5 files.

### Minimal example:
performed steps | average speed | size of .h5
~100 | 3.00s/it | 10 MB
~10000 | average 20.00s/it | 1GB
~20000 | average 33.00s/it | 2GB

**Comment by dfm** [comment]
Hi @MNGuenther, this is pretty strange. Can you please send a snippet of code that demonstrates this (not just the timing) so that I can try to track it down?

**Comment by dfm** [comment]
I still can't reproduce this issue - I can easily run 20,000 samples without any noticeable slow down. Please feel free to re-open this issue with a snippet of code that reproduces your problem if it continues!

**Comment by dfm** [comment]
P.S: here is my notebook testing this out: https://gist.github.com/dfm/ecc39487920a31c1a01fdfa4f70e68f0
