### ISSUE TITLE
Exception while calling your likelihood function

### ISSUE THREAD

**Issue by svretina** [dfm/emcee#255]
**General information:**

- emcee version: Latest
- platform: Fedora27
- installation method (pip/conda/source/other?): pip3

**Problem description:**

### Expected behavior:
to fit  my observational data to my model: d_l = (1+z) \int_0^z c/(H_0 * \sqrt(\Omega_m*(1+z)^3+\Omega_\Lambda))
### Actual behavior:
```
[stamatis@astro Astrophysics]$ ./emcee_fit.py 
===========================================start==============================
emcee: Exception while calling your likelihood function:
  params: [ 0.65500658  0.11251524]
emcee: Exception while calling your likelihood function:
emcee: Exception while calling your likelihood function:
  params: [ 0.42544128  0.25286235]
  params: [ 0.46441115  0.17217373]
emcee: Exception while calling your likelihood function:
  params: [ 0.84313632  0.71857167]
  args: (array([ 0.028488  ,  0.050043  ,  0.052926  ,  0.070086  ,  0.062668  ,
        0.087589  ,  0.078577  ,  0.017227  ,  0.042233  ,  0.045295  ,
        0.03648   ,  0.019599  ,  0.100915  ,  0.027342  ,  0.074605  ,
        0.026489  ,  0.049922  ,  0.030604  ,  0.01634564,  0.0154363 ,
        0.030529  ,  0.024525  ,  0.023953  ,  0.026038  ,  0.048948  ,
        0.024314  ,  0.015166  ,  0.03572   ,  0.048818  ,  0.02198001,
        0.1244    ,  0.036     ,  0.016321  ,  0.01673   ,  0.0275    ,
        0.021793  ,  0.01645   ,  0.023208  ,  0.036457  ,  0.019264  ,
        0.017605  ,  0.031528  ,  0.023536  ,  0.016743  ,  0.05371   ,
        0.016991  ,  0.027865  ,  0.017173  ,  0.029955  ,  0.016559  ,
```
### What have you tried so far?:
I tried to work around the definition of my model and the likelihood function but couldnt find what's wrong. For a different problem I defined everything in the same philosophy and it worked. I am new in mcmc methods and trying to learn this package. Sorry, if I am asking something too obvious.
### Minimal example:

```#!/usr/bin/python3

import numpy as np 
import matplotlib.pyplot as plt 
import emcee
from scipy.linalg.lapack import dgtsv,cgtsv
from scipy.interpolate import interp1d
from scipy.integrate import  simps
import os
import scipy.fftpack
from scipy import stats
from scipy import signal
import corner
import scipy.constants as const



H0 = 70.022
z,mu_obs,sigma_obs = np.loadtxt("Union21.txt",usecols=(1,2,3),unpack=True,dtype=np.float64)

dl_obs = np.exp(mu_obs/5-5)
sigma_dl_obs = (1./5.)*np.exp(mu_obs/5.-5.)*sigma_obs

# MCMC
x = z
y = dl_obs
yerr = sigma_dl_obs


def func(z,Omega_m,Omega_lambda):
        z_vec = np.linspace(0,z,1000)
        f = const.c/(H0*np.sqrt(Omega_m*(1+z_vec)**3+Omega_lambda))
        model = (1+z)*simps(f,x=z_vec)
        return model




ndim, nwalkers = 2 , 1000


def lnlike(theta, x, y, yerr):
        Omega_m,Omega_lambda  = theta
        model = func(x,Omega_m,Omega_lambda)
        inv_sigma2 = 1.0/(yerr**2 )
        lnp1 = -0.5*(np.sum((y-model)**2*inv_sigma2 - np.log(inv_sigma2)))
        return lnp1 


def lnprior(theta):
	Omega_m,Omega_lambda  = theta
	if 0 <= Omega_m <= 1 and  0 <= Omega_lambda <= 1:
		return 0.0
	return -np.inf


def lnprob(theta, x, y, yerr):
        lp = lnprior(theta)
        if not np.isfinite(lp):
                return -np.inf
        return lp + lnlike(theta, x, y, yerr)    


pos = [ np.array([ np.random.uniform(0,1) ,  np.random.uniform(0,1)]) for i in range(nwalkers)]


sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=(x, y, yerr),threads=4)
file1 = open('cosmological_parameters.txt', 'w')

print ('===========================================start==============================')

iiter=1
for result in sampler.run_mcmc(pos, 2000):
	pos = result[0]
	for i in range(len(pos)):
		file1.write(str('%s %s %s\n') % (pos[i][0],pos[i][1]))
	os.system("clear")
	print ("######  STATUS  ######")
	print ("iteration : " , iiter)
	print ("######################")
	iiter=iiter+1


file1.close()

print("Loading results")

Omega_m,Omega_lambda = np.loadtxt("cosmological_parameters.txt",delimiter=" ",unpack=True)
burn = 10000
Omega_m = Omega_m[burn:]
Omega_lambda = Omega_lambda[burn:]

print("Computing estimators")

N = int(np.sqrt(len(Omega_lambda)))
n = len(Omega_lambda)

data = np.vstack([Omega_m, Omega_lambda])
data = np.reshape(data,(n,2))
print(data.shape)
figure = corner.corner(data, bins=300,labels=[r"$\Omega_m$", r"$\Omega_{/Lambda}$"],
                       quantiles=[0.16, 0.5, 0.84],
                       show_titles=True, title_kwargs={"fontsize": 12})


plt.show()
```

**Comment by svretina** [comment]
I run is for 1 iteration on 1 thread and more info about the issue:
  exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "./emcee_fit.py", line 61, in lnprob
    return lp + lnlike(theta, x, y, yerr)
  File "./emcee_fit.py", line 43, in lnlike
    model = func(x,Omega_m,Omega_lambda)
  File "./emcee_fit.py", line 31, in func
    z_vec = np.linspace(0,z,101)
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/function_base.py", line 120, in linspace
    if step == 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "./emcee_fit.py", line 73, in <module>
    for result in sampler.sample(pos, iterations=1):
  File "/usr/local/lib/python3.6/site-packages/emcee/ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "/usr/local/lib/python3.6/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/usr/local/lib/python3.6/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "./emcee_fit.py", line 61, in lnprob
    return lp + lnlike(theta, x, y, yerr)    
  File "./emcee_fit.py", line 43, in lnlike
    model = func(x,Omega_m,Omega_lambda)
  File "./emcee_fit.py", line 31, in func
    z_vec = np.linspace(0,z,101)
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/function_base.py", line 120, in linspace
    if step == 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by dfm** [comment]
There is a bug in your `func` function. When you call it `z` is an array and you can't evaluate `linspace` with one of the arguments being an array.
