### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by MaxNoe** [dfm/emcee#258]
As we have an upcoming publication using 3.0dev, it would be great to have a fixed version we can cite.

Could you release a 3.0-rc1 or similar?

**Comment by dfm** [comment]
Good call! I've added a 3.0rc1 release and it has the DOI: https://doi.org/10.5281/zenodo.1297477 (this hasn't resolved yet, but it will soon). Thanks and please let me know if you need anything else or if you run into issues!

**Comment by MaxNoe** [comment]
Thanks a lot!

Did you also upload it to PyPI? It allows pre-releases that are not installed by default unless specifically asked for.

**Comment by dfm** [comment]
done.

**Comment by MaxNoe** [comment]
Thanks!
