### ISSUE TITLE
Threaded Processes not Killed After Sampling

### ISSUE THREAD

**Issue by spencerscott917** [dfm/emcee#259]
**General information:**

- emcee version: 2.2.1
- platform: Linux
- installation method (pip/conda/source/other?): conda

**Problem description:**

### Expected behavior:
After multithreaded sampler finishes running, python processes used to be killed

### Actual behavior:
After multithreaded sampler finished running, processes are left open

### What have you tried so far?:
I have consulted the documentation and searched GitHub for similar issues or fixes.

### Minimal example:

Here is how I am implementing an emcee sampler within my code. When there are multiple threads, it starts new python processes as expected, but the processes are never killed when the sampler 

```python
import emcee

sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, threads=nthreads)
pos, prob, state = sampler.run_mcmc(p0, 1000) # p0 contains the initial walker positions

```

**Comment by dfm** [comment]
To get your intended behavior, you should do something like:

```python
import emcee
from multiprocessing import Pool

with Pool() as pool:
    sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, pool=pool)
    pos, prob, state = sampler.run_mcmc(p0, 1000) # p0 contains the initial walker positions
```

This is exactly why the `nthreads` keyword will be removed in the next release 😄.

**Comment by spencerscott917** [comment]
Oh perfect, thank you!
