### ISSUE TITLE
Add a docstring for `State`/add to docs

### ISSUE THREAD

**Issue by eteq** [dfm/emcee#264]
I think this is pretty trivial (and might be able to get around to it myself), but want to make sure there's not some reason to avoid this (like `State` is still in flux).

Since `State` is now potentially important as the return (and possible input) of `sample`/`run_mcmc`, it probably makes sense to have it documented and get an ``autoclass`` somewhere in the docs, right?

**Comment by dfm** [comment]
Absolutely!
