### ISSUE TITLE
Obtaining different values with autocorr.integrated_time()

### ISSUE THREAD

**Issue by Gabriel-p** [dfm/emcee#265]
**General information:**

- emcee version: 2.2.1
- platform: Ubuntu 16.04 64 bit
- installation method (pip/conda/source/other?): conda

**Problem description:**

I'm getting different results when using `autocorr.integrated_time()` on an `emcee` trace for multiple parameters.

### Expected behavior:

The same values should be returned with both methods.

### Actual behavior:

Values are not equal.

### Minimal example:

My code is too large to post a complete working example here, but I believe the issue can be understood either way.

```python
import emcee

# Define sampler
sampler = emcee.EnsembleSampler(...)
# I'm using ndim=6
emcee_trace = sampler.chain.reshape(-1, ndim).T
# emcee_trace.shape = (6, nwalkers*nsteps)

# Checking autocorrelation with two methods.
# I use c=5 otherwise it fails with my actual data:
m1 = emcee.autocorr.integrated_time(emcee_trace.T, c=5)
m2 = [emcee.autocorr.integrated_time(_, c=5) for _ in emcee_trace]

# m1
array([ 630.31740613, 1427.70336924,  684.47860593, 1043.86558911,
        613.30684834,  356.69468562])
# m2
[851.2933101013339, 1427.7033692352315, 1034.205460451514, 1142.0326324415114,
821.0257568805758, 577.6751150976922]
```

I find it strange that the second value is exactly equal in both cases, but none other. Shouldn't they all be equal?

**Comment by Gabriel-p** [comment]
Thank you for your comments Dan. I understand why using the flat chain to obtain the AT would be problematic.

I checked the `integrated_time` function. A few comments:

1. It mentions an `axis` parameter which is not present (probably left over from the old function)
1. If I pass the entire `sampler.chain` (`sampler.chain.shape=(nchains, nsteps, ndims)`) to `integrated_time()` it returns very low (<1.) estimates for each parameter. If instead I pass one chain at at time, I get reasonable estimates.

**Comment by dfm** [comment]
The docstring is old, but there isn't a bug on those lines because the shape of the chain has been changed on the master branch. It will definitely have to be changed to use with older versions.

**Comment by Gabriel-p** [comment]
Thanks again for the clarification!
