### ISSUE TITLE
Does emcee reuse likelihood values for a repeated parameters vector?

### ISSUE THREAD

**Issue by Gabriel-p** [dfm/emcee#273]
This is not an issue, rather a question.

My likelihood is particularly costly to obtain. Since the sampler necessarily visits the same point in parameter space more than once it would be very convenient if the sampler, instead of processing the full likelihood every time, took the value from the stored array of values.

Does `emcee` do this already? If not, is there a specific reason for not doing it, or it just isn't implemented?

**Comment by andyfaff** [comment]
> My likelihood is particularly costly to obtain. Since the sampler
necessarily visits the same point in parameter space more than once it
would be very convenient if the sampler, instead of processing the full
likelihood every time, took the value from the stored array of values.

In general caching or memoisation is harder when arrays are being used as
arguments. In the cache one would need to store a unique hash for a given
array, associated with the probability. The calculation of the hash would
create overhead, which might be too significant when the probability
functions are cheap to calculate.

**Comment by andyfaff** [comment]
In fact it may be something you can implement yourself without having to do
it in emcee:

https://pythonhosted.org/joblib/memory.html

You could use the memory.cache decorator on your log-likelihood function.

**Comment by Gabriel-p** [comment]
That looks promising, thank you @andyfaff!

**Comment by andyfaff** [comment]
It's not clear to me though that emcee revisits the same parameter vector. It only calculates the log probability for the new coordinates, the log-probability is stored for the existing coordinates.

**Comment by Gabriel-p** [comment]
But at some point it is bound (I think) to re-visit the same parameter vectors after exploring the area for a large enough time. Or is the probability of this happening so small that caching likelihoods is irrelevant?

**Comment by Gabriel-p** [comment]
If I understand correctly, this vanishing probability is because the parameters are assumed continuous and with no rounding of the floats.

What would happen if I work with discrete parameters and/or rounded floats?

**Comment by dfm** [comment]
It might help in that case and you could probably do something simpler than using joblib, but if all of your parameters are discrete then you're unlikely to get good performance from emcee anyways...

**Comment by Gabriel-p** [comment]
Thanks Dan. Half of my parameters are discrete and I actually already tried to store processed models and their likelihoods manually to reuse later. It didn't help, so I guess that's that.
