### ISSUE TITLE
Update sampler "on the fly"?

### ISSUE THREAD

**Issue by Gabriel-p** [dfm/emcee#274]
The [Nelson et al. (2014)](http://adsabs.harvard.edu/abs/2014ApJS..210...11N) article (the source for the the [DEMove() class](https://emcee.readthedocs.io/en/latest/user/moves/#emcee.moves.DEMove)) discusses a strategy to achieve reasonable acceptance ratios:

> Since values of γ close to 1 can be useful for multimodal posterior distributions, it can be advantageous to occasionally choose γ near unity. However, most trial states should use a smaller value of γ to achieve a desirable acceptance ratio. Therefore, we arbitrarily set γ to 1 every 100 generations.
> The value of γ can be updated after every generation throughout a RUN DMC simulation. We aim for an acceptance fraction of 0.25. If too few states are being accepted (<0.2), γ is scaled by 0.9 in the hope that smaller jumps will lead to a higher acceptance fraction. If the acceptance fraction exceeds 0.31, then γ is scaled by 1.1 to allow for larger jumps (...) In DEMCMC, this procedure references information from only one previous generation of states, so our algorithm is still Markov for each generation. 

This involves updating the sampler mid-run. Can this be done with `emcee`?

**Comment by dfm** [comment]
To implement something like this, I'd recommend using a mixture of moves. e.g.:

```python
import emcee
from emcee import moves
moves = [
    (moves.DEMove(..., gamma0=0.1), 0.99),
    (moves.DEMove(..., gamma0=1.0), 0.01),
]
sampler = emcee.EnsembleSampler(..., moves=moves)
```

After burn-in, you can probably update the move:

```python
moves[0].gamma0 = new_gamma0
```

but I haven't tested this in detail.

**Comment by Gabriel-p** [comment]
Didn't think of doing that. Thank you Dan!
