### ISSUE TITLE
Confused by definition of DEMove()

### ISSUE THREAD

**Issue by Gabriel-p** [dfm/emcee#275]
(Sorry for flooding the repo with questions, please let me know if this is not the place for this)

I'm trying to understand the new [`DEMove()` class](https://emcee.readthedocs.io/en/latest/user/moves/#emcee.moves.DEMove) based on the [Nelson et al. (2014)](http://adsabs.harvard.edu/abs/2014ApJS..210...11N
) article, which in turn is based on the [Ter Braak (2006)](https://link.springer.com/article/10.1007/s11222-006-8769-1) article. I'm following the definition of the displacement vector, and I can see the following:

* Braak: `x_p = x_i + gamma_0 * Delta(x) + N` ; Eq (2)
* Nelson: `x_p = x_i + gamma_0 * (1 + N) * Delta(x)` ; Eq (10)
* emcee: `x_p = x_i + (1 + gamma_0 * N) * Delta(x)` ; [L49](https://github.com/dfm/emcee/blob/8a473d577a767254e378e04e153b829dfbee1916/emcee/moves/de.py#L49)

(where `N` is a draw from a Gaussian) None of these three definitions match as far as I cant tell, which clearly means I'm not understanding something obvious here.

**Comment by dfm** [comment]
This might be a bug in the emcee implementation. It also seems to me that the three definitions are different (I'm pretty sure that they would all produce *correct* samplings - but one might be more efficient than the others) but I don't remember running into this definition issue when I originally worked through the details. I'll try to take a closer look soon.

**Comment by dfm** [comment]
I've switched the notation to be the same as the Ter Braak version. The performance seems good and I don't really know what I had done before :/

Thanks for bringing this up!
