### ISSUE TITLE
run_mcmc overwrites initial state array

### ISSUE THREAD

**Issue by adrn** [dfm/emcee#276]
**General information:**

- emcee version: 3.0rc1
- platform: Mac OS X
- installation method (pip/conda/source/other?): source

**Problem description:**

`sampler.run_mcmc(p0)` updates in-place the values in `p0`

Example:

```python
import numpy as np
import emcee
rnd = np.random.seed(42)

def ll(x):
    return -0.5 * np.sum(x**2)

nwalkers = 64
p0 = np.random.normal(size=(nwalkers, 1))
print(p0[:4])
print()

sampler = emcee.EnsembleSampler(nwalkers, 1, ll)
_ = sampler.run_mcmc(p0, 100)
print(p0[:4])
```

Outputs:
```
[[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]
 [ 1.52302986]]

[[-0.95042763]
 [-1.45356148]
 [-0.42794939]
 [ 1.24097786]]
```

Do you recommend doing
```python
_ = sampler.run_mcmc(p0.copy(), 100)
```
instead when passing in arrays, or is this a bug?

<3

**Comment by dfm** [comment]
That definitely seems like a bug. I probably introduced it when I switched to using `State`s. I'll look into it next week. Thanks!

**Comment by dfm** [comment]
Finally got to this. Everything should work as expected now!
