### ISSUE TITLE
[0.3rc1] Tests missing in pypi tarball

### ISSUE THREAD

**Issue by olebole** [dfm/emcee#277]
Hi,

I am the Debian maintainer of the [emcee package](https://tracker.debian.org/pkg/emcee), and I am currently checking the latest RC for an update. I use the source package from Pypi to create the Debian package.

To ensure that everything works, we usually try to run the tests both at package build time, and as CI on the installed package whenever one of the dependencies changes.

In version 3.0, the tests were moved from `emcee/tests` to `tests/` in the package root in the github repository; however they are not included in the Pypi package, so that I can't run the tests anymore.

Would it be possible to to add the `tests` subdir to the pypi package as well?

Thanks!

Best regards

Ole

**Comment by dfm** [comment]
Thanks for getting in touch. I've tried to fix this in e68ef34 and it'll be included in the next release candidate. Let me know if there are any issues related to this or anything else. Thanks!

**Comment by olebole** [comment]
Oh, sorry that I didn't close this earlier. It fixed, thank you very much!
