### ISSUE TITLE
Broken link on the RTD page

### ISSUE THREAD

**Issue by tmcclintock** [dfm/emcee#282]
On the [RTD page](https://emcee.readthedocs.io/en/stable/) there are supposed to be two links to the quickstart documentation. One is in the sentence "A more complete example is available in the [quickstart documentation](https://emcee.readthedocs.io/en/stable/user/quickstart)." and the other is the [Quickstart link](https://emcee.readthedocs.io/en/stable/user/quickstart.html). The former link is missing a .html and goes to the maze page.

I tried to fix this myself, but the current [docs/index.rst](https://github.com/dfm/emcee/blob/master/docs/index.rst) seems to be inconsistent with the RTD page (e.g. the former has a section heading "How to use this guide" while the RTD page as it labeled "User Guide"), so I'm not sure where RTD is building from.

**Comment by dfm** [comment]
Yeah - the "stable" docs are a bit of a mess. The RTDs build of the master branch can be found here: https://emcee.readthedocs.io/en/latest and I think that all the links are ok there.

**Comment by tmcclintock** [comment]
I see. Then I'll close this and you can decide whether you want to get rid of the stable docs or not.
