### ISSUE TITLE
RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by huhell** [dfm/emcee#298]
**General information:**

- emcee version: 2.2.1
- platform: Ubuntu LTS 18.04
- installation method (pip/conda/source/other?): pip

**Problem description:**

### Expected behavior:
No error

### Actual behavior:
I get a RuntimeWarning: invalid value encountered in double_scalars in the red_blue.py script at line 97: lnpdiff = f + nlp - state.log_prob[j]. The same error appears from the old ensemble.py script at the line: lnpdiff = (self.dim - 1.) * np.log(zz) + newlnprob - lnprob0 (Issue 269, now closed)

### What have you tried so far?:
I have tried both versions of the code, and I can't figure out why I get that error. For an Ensemble with a lower amount of steps I do not get that error, only when the chain gets longer.

### Minimal example:

```python
import emcee



# sample code goes here...
```

**Comment by dfm** [comment]
This generally means that you are initializing in some part of parameter space where the log probability is -inf or nan. Double check that your initialized values are all ok. If they are, then there's a chance that this is caused by your log probability function returning nan or inf, but that should be caught in the sampler. One way or another you should always try to catch issues like that in your log probability function and return `-np.inf`. Give that a shot.

**Comment by huhell** [comment]
Thanks, I already control the priors on my parameters, as well as the log probability which returns -np.inf in case of issues..

**Comment by dfm** [comment]
I'm not sure what you mean by "control", but this does mean that there's some numerical issue happening in your log probability function and it normally has to do with initialization. I'd recommend trying to make a simple test case that reproduces the problem. That should make it clear what's going on.

**Comment by huhell** [comment]
Alright, I'll check all this. Thanks again.

**Comment by ayushp88** [comment]
> I'm not sure what you mean by "control", but this does mean that there's some numerical issue happening in your log probability function and it normally has to do with initialization. I'd recommend trying to make a simple test case that reproduces the problem. That should make it clear what's going on.

Sir I am also facing the same issue, can you please help me.
