### ISSUE TITLE
ValueError: algorithm must be 'MT19937' when creating sampler

### ISSUE THREAD

**Issue by iipr** [dfm/emcee#299]
**General information:**

- emcee version: v3.0rc2
- platform: Ubuntu 18.04.1 LTS
- installation method (pip/conda/source/other?): pip install emcee==3.0rc2

**Problem description:**
Running `emcee.EnsembleSampler()` throws error.

### Expected behavior:
No error, creating the sampler correctly.

### Actual behavior:
`ValueError: algorithm must be 'MT19937'`

### What have you tried so far?:
The error is coming from `emcee/ensemble.py`, line 133. I tried printing `state` variable, and it seems like the first element of this list, which should be `'MT19937'` is in reality `b'MT19937'`. So it seems like it is a bytes string. As a quick fix I tried setting `state[0] = 'MT19937'` just before the call to `set_state` and it seems to work fine, although this solution is obviously no good.

### Minimal example:

```python
import emcee
# File with posterior class:
import posterior as pos
posterior = pos.posterior()
filename = 'test.chains'
name = '000'
ndim = 3
nwalkers = 10
max_n = 10000

backend = emcee.backends.HDFBackend(filename, name=name) 
sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob_fn=posterior.lnpos, 
                                args=[[ns_range[0], ns_range[1]],[]], backend=backend)
```

**Comment by dfm** [comment]
Interesting. Thanks for reporting this. This definitely isn't the expected behavior. I'll look into this.
What version of Python are you on, just so I know?

**Comment by iipr** [comment]
I was running Python 3.6.6

**Comment by ogoann** [comment]
I am seeing the same error, and the fix proposed above works for me as well (thanks @iipr for posting!). 

emcee: 3.0.0, installed via conda
python: 3.7.3
platform: Scientific Linux 7.7

**Comment by ogoann** [comment]
There you go! The code assumes that an h5 file already exists. I have tested this on multiple h5 files, which I was able to open without this error with python 2.7 . 

```python
import emcee
filename = 'chain.h5' # already existing chain file
backend = emcee.backends.HDFBackend(filename)
nwalkers = backend.shape[0]
ndim = backend.shape[1]
#following line results in error
sampler = emcee.EnsembleSampler(nwalkers, ndim, None, backend=backend)
```

**Comment by dfm** [comment]
How are you creating that file? I'm not getting an error here.

**Comment by ogoann** [comment]
Hi, 

Initially I was seeing this error while working with files created with python 2.7. However, now that I am running new chains from scratch (no old chains), I see the same exact error as well. Except that @iipr's solution does not work, because "state" is a tuple, so instead I do:

```python
state = list(state)
state[0] = 'MT19937'
state = tuple(state)
```

Minimal example:

```python
import emcee

def lnprob(x):
	return 0

nwalkers = 4
ndim = 1
sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob)
```
with the error specifically being: 
```
File "mtrand.pyx", line 788, in mtrand.RandomState.set_state
ValueError: algorithm must be 'MT19937'
```

**Comment by dfm** [comment]
Wait - are you sure that exactly that code snippet (without any hdf5 file) gives you that error? If so, there's a bug with your numpy that we can look into.

**Comment by ogoann** [comment]
Yes, I'm sure (just triple checked).

**Comment by dfm** [comment]
Weird - what happens if you run:

```python
import numpy as np
np.random.mtrand.RandomState().set_state(np.random.get_state())
```

**Comment by dfm** [comment]
And just to confirm, this is the code that throws that error:

```python
import emcee

def lnprob(x):
    return 0

nwalkers = 4
ndim = 1
sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob)
```

**Comment by dfm** [comment]
And finally, what's the output of:

```bash
python --version
python -c "import emcee;print(emcee.__version__)"
python -c "import numpy;print(numpy.__version__)"
```

**Comment by ogoann** [comment]
```
np.random.mtrand.RandomState().set_state(np.random.get_state())
```
executes without errors. Having this before calling ```emcee.EnsembleSampler``` does not help.

```bash
$ python --version
Python 3.7.3
$ python -c "import emcee;print(emcee.__version__)"
3.0.0
$ python -c "import numpy;print(numpy.__version__)"
1.16.4
````

And yes, that is a minimal example of code that throws this error.

**Comment by dfm** [comment]
Very strange! I've set up exactly the same environment and I can't reproduce this issue anywhere. First can you send me the full traceback of the error. Then you might just want to try updating numpy and emcee to see if that fixes it!

**Comment by ogoann** [comment]
Updating to ```numpy 1.17.3``` and ```emcee 3.0.1``` seems to have solved this issue for me! It think I also upgraded lots of packages along the way, so hard to say what really did the trick.

**Comment by ogoann** [comment]
I guess for posterity the original full traceback was: 

```python
$ python example.py 
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob)
  File "/local/data/lemssd/amogorza/local/src/anaconda3/lib/python3.7/site-packages/emcee/ensemble.py", line 156, in __init__
    self._random.set_state(state)
  File "mtrand.pyx", line 788, in mtrand.RandomState.set_state
ValueError: algorithm must be 'MT19937'
```

When I updated just ```numpy``` but not yet ```emcee```. the error changed to:
```python
$ python example.py 
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob)
  File "/local/data/lemssd/amogorza/local/src/anaconda3/lib/python3.7/site-packages/emcee/ensemble.py", line 156, in __init__
    self._random.set_state(state)
  File "mtrand.pyx", line 274, in numpy.random.mtrand.RandomState.set_state
TypeError: state must be a dict or a tuple.
```

**Comment by dfm** [comment]
Thanks! That's very strange, but I'm glad that it is now sorted even if we don't know why :/
