### ISSUE TITLE
Potential bug in run_mcmc of the 2.2.x branch

### ISSUE THREAD

**Issue by AlexisPrel** [dfm/emcee#300]
**General information:**

- emcee version: 2.2.x

**Problem description:**
Reading the [code for the Sampler class](https://github.com/dfm/emcee/blob/v2.2.x/emcee/sampler.py) of version 2.2.x, I think I found a mistake at line **167** in `sampler.py`: 

Shouldn't `rstate0` be replaced with `lnprob0` ?

**Comment by dfm** [comment]
Yes! You're absolutely right.
