### ISSUE TITLE
No change in acceptance fraction when changing the 'a' parameter (emcee 3.0)

### ISSUE THREAD

**Issue by kmarr** [dfm/emcee#301]
**General information:**

- emcee version:  3.0rc2
- platform:  Ubuntu 18.10
- installation method (pip/conda/source/other?):  source

**Problem description:**

### Expected behavior: 
The acceptance fraction should change when using different 'a' parameters. 

### Actual behavior: 
The acceptance fraction stays the same no matter what value is used for 'a'.

### What have you tried so far?: 
In version 3.0rc2, a range of values for 'a', from 1.0 to 50.0, none of which change the acceptance fraction. In version 2.2.1, this does work, so I have reverted back to that version for now.

### Minimal example:

```python
# Slightly modifying example code from the emcee website (https://emcee.readthedocs.io/en/latest/tutorials/quickstart/)

import numpy as np
import emcee
print(emcee.__version__)

def log_prob(x, mu, cov):
    diff = x - mu
    return -0.5*np.dot(diff, np.linalg.solve(cov,diff))

a_parameter=2.0

ndim = 5

np.random.seed(42)
means = np.random.rand(ndim)

cov = 0.5 - np.random.rand(ndim ** 2).reshape((ndim, ndim))
cov = np.triu(cov)
cov += cov.T - np.diag(cov.diagonal())
cov = np.dot(cov,cov)

nwalkers = 32
p0 = np.random.rand(nwalkers, ndim)

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, args=[means, cov], a=a_parameter)

log_prob(p0[0], means, cov)

state = sampler.run_mcmc(p0, 100)

af = np.mean(sampler.acceptance_fraction)
print(af)


# emcee 3.0rc2 output
# 3.0rc2
# 0.5484375 <-- Does not change when using different a_parameter, or when rerunning code

#emcee 2.2.1 output
# 2.2.1
# 0.5440625 <-- Changes when using different a_parameter, and changes by statistical fluctuations when rerunning
```

**Comment by dfm** [comment]
In version 3, you need to use something like the following:

```python
move = emcee.moves.StretchMove(a=a_parameter)
sampler = emcee.EnsembleSampler(..., moves=[move])
```

See [the docs](https://emcee.readthedocs.io/en/latest/user/moves/#emcee.moves.StretchMove).

**Comment by kmarr** [comment]
This fixes my issue. Thanks for your quick response.
