### ISSUE TITLE
`sampler.sample` cannot be used to resume chains

### ISSUE THREAD

**Issue by gboehl** [dfm/emcee#305]
**General information:**

- emcee version: 3.0.rc2
- platform: Linux 5.2.8, Python 3.7.4
- installation method (pip/conda/source/other?): add path to local repo

**Problem description:**
I'm integrating emcee into one of my packages. It is important that chains can be resumed. This works well if using `sampler.run_mcmc(None, n)`, but fails with iterating over `sampler.sample(None, n)`.

### Actual behavior:
`ValueError: incompatible input dimensions`

### Minimal example:

```python
import emcee
import numpy as np

def log_prob(theta):
    log_prior = -0.5 *  np.sum((theta-1.0)**2 / 100.0)
    log_prob = -0.5 * np.sum(theta**2) + log_prior
    return log_prob, log_prior

coords = np.random.randn(32, 5)
nwalkers, ndim = coords.shape

filename = "tutorial.h5"
backend = emcee.backends.HDFBackend(filename)

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend)

max_n = 1000

sampler.run_mcmc(coords, max_n, progress=True)

new_sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend)

new_sampler.run_mcmc(None, max_n, progress=True)    # works :)

for _ in new_sampler.sample(None, iterations=max_n, progress=True):  # does not work :(
    continue
```
Many thanks for this great package!

**Comment by gboehl** [comment]
Turns out, the `iterations=` keyword is necessary... closing.

**Comment by dfm** [comment]
Thanks for this! There are some (perhaps weak) reasons why that doesn't work in the current implementation, but there is an easy workaround that could be integrated more seamlessly:

```python
new_sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend)

state = new_sampler.get_last_sample()

for _ in new_sampler.sample(state, iterations=max_n, progress=True):  # should work now!
    continue
```

Hope that helps!

**Comment by gboehl** [comment]
It does, thanks a lot! I'm keeping this open, but feel free to close it.
