### ISSUE TITLE
emcee 3.0 breaks extended-precision coordinates

### ISSUE THREAD

**Issue by aarchiba** [dfm/emcee#312]
We are working with variables of type np.longdouble (hardware 80-bit floating-point, stored in np.float96 or np.float128 depending on platform), and the switch from emcee 2.2 to emcee 3.0 breaks using these as walker coordinates. Specifically, np.linalg is not capable of doing linear algebra on these extended-precision values, but scipy.linalg is, and sample() calls np.linalg.det on a covariance matrix constructed from these coordinates.

One option would be to try to import linalg from scipy, and fall back to numpy if this is not available; this would have a higher chance of using faster system BLAS packages too, and it's reasonable to fail to work if no high-precision implementation is available (we require scipy anyway). 

If the determinant is an approximate value, for example it is applied to a covariance matrix for a small sample, then it might be harmless and simple to just apply .astype(float) to the covariance matrix. Of course determinants can be numerically precarious, but the determinant call is checking for approximate linear dependence, so it's probably just fine to approximate. 

We are using this in PINT ( https://github.com/nanograv/PINT ) which works with time spans of decades that can be measured to the nanosecond, so we really do need the extended precision, though often by the time we are down to the quantities of real interest the need for precision is less.

**Comment by dfm** [comment]
Thanks for this update! I think that a good temporary workaround would be to pass `skip_initial_state_check = True` to sample, but I'll try out your proposed options for a better long term solution.

**Comment by aarchiba** [comment]
If I were to write up a few test cases to confirm that emcee worked okay with extended precision, would that be a good addition to the test suite? Nothing too elaborate.

**Comment by dfm** [comment]
That would be wonderful if you get a chance!

**Comment by aarchiba** [comment]
Turns out the assumption that walker coordinates are floats is baked into the chain storage. Do you want to also allow complex coordinates? I mean I think the affine thing should work fine there, so it's just a matter of allowing the dtype?

**Comment by aarchiba** [comment]
(Incidentally although https://github.com/aarchiba/triplesystem used emcee, I was using downhill optimizers as well and so I handed them all normalized coordinates that were of about zero mean and order unity standard deviation. It sure didn't simplify things any, though.)

**Comment by dfm** [comment]
Interesting. Let me think a bit more about complex coordinates, but I think it definitely makes sense to support different dtypes for the coordinates in general. I'll look into how much that'll take to do.

**Comment by aarchiba** [comment]
I think the easy way would be to just specify the dtype when constructing a backend and all would be fine. With a little more cleverness one could take advantage of the dtype information in an hdf5 file when opening an existing one (instead of just raising an exception if the two differ). Otherwise it's mostly a matter of tracing type cleanliness through the code, which is probably most easily done by arranging values like 1+np.finfo(np.longdouble).eps so it's obvious where they've been mangled.

**Comment by davidwhogg** [comment]
I think the only true constraint on the parameter space is that it have the algebra of a vector space. But I'm not sure I have enough math to be confident about what the true conditions are. Certainly complex numbers DO meet the criteria.

**Comment by aarchiba** [comment]
The parameter space must also be spanned by real affine combinations of the walkers. Which means you need twice as many walkers for a complex space; not a big deal but it would require more checking. 

I did some experimentation and got the default backend working with long doubles but am having mysterious failures with HDF5 that I haven't tracked down. Perhaps I can put up a WIP PR.

**Comment by dfm** [comment]
@aarchiba: Awesome! Yes - please open that pull request and I can try to make some suggestions there.

**Comment by dfm** [comment]
Fixed by #319
