### ISSUE TITLE
emcee won't run from source

### ISSUE THREAD

**Issue by tlatorre-uchicago** [dfm/emcee#321]
**General information:**

- emcee version: master
- platform: Linux
- installation method (pip/conda/source/other?): source

**Problem description:**

When trying to install emcee from source it seems that the emcee_version.py file never gets created, and so I'm getting an ImportError.

### Expected behavior:

```python
>>> import emcee
```

### Actual behavior:

```python
>>> import emcee
ImportError: No module named emcee_version
```

### What have you tried so far?:

I grepped through the code base looking for an emcee_version.py file and noticed that it's in the .gitignore, so I guess it's a file which isn't stored in the git repository.

I bisected the problem to 13595f7c04f6e0711cc34567e398576e375043bc which is where the emcee_version.py file was introduced.

### Minimal example:

```bash
$ git clone https://github.com/dfm/emcee
$ cd emcee
$ python setup.py install
$ cd ~
```
and then try to import it:

```python
>>> import emcee
```

**Comment by dfm** [comment]
This is probably because `setuptools_scm` must be installed before running `setup.py`. What happens if you do:

```bash
pip install .
```

If that doesn't work,

```bash
pip install -U setuptools setuptools_scm
python setup.py install
```

should do the trick. Let me know and we'll update the docs!

**Comment by tlatorre-uchicago** [comment]
Just trying pip install fails with:

```bash
(emcee_env) [tlatorre@localhost emcee]$ pip install .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /home/tlatorre/emcee
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/tlatorre/emcee_env/bin/python2 /home/tlatorre/emcee_env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp3XO2W1
         cwd: /tmp/pip-req-build-ObXBAv
    Complete output (2 lines):
    running dist_info
    error: 'egg_base' must be a directory name (got `/tmp/pip-modern-metadata-GV2AR8`)
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tlatorre/emcee_env/bin/python2 /home/tlatorre/emcee_env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp3XO2W1 Check the logs for full command output.
```

I didn't try the second approach but was able to get it to work with the changes in #322.

**Comment by dfm** [comment]
This is a completely separate error, but I bet it's related to py2.7 which we can no longer support!

**Comment by dfm** [comment]
I think we found a solution over in #322 and I've added some more instructions to the docs so I'm going to close. Feel free to reopen if there are remaining issues.
