### ISSUE TITLE
Problem using "backends"

### ISSUE THREAD

**Issue by mdzrod** [dfm/emcee#336]
**General information:**

- emcee version: 3
- platform: Linux
- installation method (pip/conda/source/other?): pip

**Problem description:**

### Minimal example:

Script 1: Save Chains

```python
import emcee

ndim, nwalkers = 2, 10
nsteps, nburn = 10000, 5000
np.random.seed(0)
filename= 'filename.h5'
backend = emcee.backends.HDFBackend(filename)
backend.reset(nwalkers, ndim)

sampler = emcee.EnsembleSampler(nwalkers,ndim,lnprob, backend=backend, args=[XX])
```

After I'm done with the code I just save it. Now, let me load it in another script:

Script 2 (separate): Load chains to make plots.

```python
import emcee
import h5py

reader = emcee.backends.HDFBackend('filename.h5', read_only=True)

tau = reader.get_autocorr_time()
burnin = int(2 * np.max(tau))
thin = int(0.5 * np.min(tau))
samples = reader.get_chain(discard=burnin, flat=True, thin=thin)

Output: AttributeError: You must run the sampler with 'store == True' before accessing the results


```

**Comment by ogoann** [comment]
Are you sure the saved h5 file actually has a chain of nonzero length in it? I get this error often when 1) the chain actually did not compute, 2) the file is corrupted because of unrelated reasons.

**Comment by mdzrod** [comment]
> Are you sure the saved h5 file actually has a chain of nonzero length in it? I get this error often when 1) the chain actually did not compute, 2) the file is corrupted because of unrelated reasons.
> 
> An easy way to check 1) is to literally watch your chain grow in size as it's being computed.

I will double check. However, even copying-paste this tutorial ([here](https://emcee.readthedocs.io/en/stable/tutorials/monitor/)) it gives the same problem. I save the chains and try to read it the same way it says at the beginning of that tutorial and it doesn't work.

**Comment by dfm** [comment]
@mdzrod: Can you post *exactly* the two scripts that you're running for this simplest case failure. (I know that you say that you're copy-pasting the tutorial, but the tutorial is *executed* to give that result so I know that it works somewhere at least 😄!) Then we can try to reproduce over here.

**Comment by mdzrod** [comment]
Sorry about that. Here it is for example:

Script 1:
```
import emcee
import numpy as np

np.random.seed(42)

# The definition of the log probability function
# We'll also use the "blobs" feature to track the "log prior" for each step
def log_prob(theta):
    log_prior = -0.5 * np.sum((theta - 1.0) ** 2 / 100.0)
    log_prob = -0.5 * np.sum(theta ** 2) + log_prior
    return log_prob, log_prior


# Initialize the walkers
coords = np.random.randn(32, 5)
nwalkers, ndim = coords.shape

# Set up the backend
# Don't forget to clear it in case the file already exists
filename = "tutorial.h5"
backend = emcee.backends.HDFBackend(filename)
backend.reset(nwalkers, ndim)

# Initialize the sampler
sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend)
```

Script 2:

```
import emcee

reader = emcee.backends.HDFBackend("tutorial.h5", read_only=True)
flatchain = reader.get_chain(flat=True)


Output: Traceback (most recent call last):
  File "test2.py", line 4, in <module>
    flatchain = reader.get_chain(flat=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/emcee/backends/backend.py", line 75, in get_chain
    return self.get_value("chain", **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/emcee/backends/hdf.py", line 123, in get_value
    "You must run the sampler with "
AttributeError: You must run the sampler with 'store == True' before accessing the results
```

Do I need to run something after sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend) ? Before attempting to use it in another script?

**Comment by dfm** [comment]
Thanks - that's exactly what I need! I'll let you know if I have any other questions.

**Comment by lukasfurtak** [comment]
I get the exact same problem and error message when running the same tutorial divided into two scripts (also with emcee v3, on linux, installed with conda).
I found out that it works if I run everything in the same script, i.e. the sample is still in memory when it reads the backend which kind of defeats the purpose of the backend...

**Comment by dfm** [comment]
Hey team,
The problem with `script1.py` above is that no steps are being run. If you add

```python
sampler.run_mcmc(coords, 10)
```

at the end, `script2.py` seems to run just fine after! If you don't find that that works for you, let me know.

**Comment by dfm** [comment]
@lukasfurtak I'm going to assume that you didn't mean

> which kind of defeats the purpose of the backend...

to be so snarky, but for future reference it's not productive to be rude like that towards volunteer supported software!

**Comment by mdzrod** [comment]
> Hey team,
> The problem with `script1.py` above is that no steps are being run. If you add
> 
> ```python
> sampler.run_mcmc(coords, 10)
> ```
> 
> at the end, `script2.py` seems to run just fine after! If you don't find that that works for you, let me know.

Hi! Thank you so much. I realized the problem was that no steps were being run, but didn't know how to fix it. Will try that.

**Comment by dfm** [comment]
Great! Let us know if you run into any other issues!
