### ISSUE TITLE
Enable HDF5 compression in the backend

### ISSUE THREAD

**Issue by privong** [dfm/emcee#338]
**General information:**

- emcee version: 3.0.2
- platform: (Arch) Linux
- installation method (pip/conda/source/other?): AUR repository

**Problem description:**
It would be nice to be able to enable compression when using HDF5 files via the emcee backends. A quick skim of the documentation and `backends/hdf.py` file suggests this isn't currently possible. Perhaps the h5py `compression=` argument could be exposed in the `emcee.backends.HDFBackend` class?

**Comment by hwajis** [comment]
بتاريخ ٣١‏/٠٣‏/٢٠٢٠ ٦:٥٦ م، كتب "George C. Privon" <notifications@github.com>:
General information:
emcee version: 3.0.2platform: (Arch) Linuxinstallation method (pip/conda/source/other?): AUR repository
Problem description:
It would be nice to be able to enable compression when using HDF5 files via the emcee backends. A quick skim of the documentation and backends/hdf.py file suggests this isn't currently possible. Perhaps the h5py compression= argument could be exposed in the emcee.backends.HDFBackend class?
