### ISSUE TITLE
unexpected backend behaviour?

### ISSUE THREAD

**Issue by Sketos** [dfm/emcee#339]
**General information:**

- emcee version: 3.0.2
- platform: macOS 10.14.6
- installation method (pip/conda/source/other?): pip

**Problem description:**

save chain with emcee.backends.HDFBackend(filename) and loading the chain to resume the run

### Expected behavior:

I would expect that after loading the ".h5" file the mcmc will resume from the last state of the chain and end once the requested nsteps are reached

### Actual behavior:

It seems that the emcee is not resuming from the last state and the total number of nsteps in the completed mcmc run is the previous steps + how many steps I request in the resumed mcmc_run()

### Minimal example: (This is taken from https://emcee.readthedocs.io/en/stable/tutorials/monitor/)

import emcee
import numpy as np

np.random.seed(42)

def log_prob(theta):
    log_prior = -0.5 * np.sum((theta - 1.0) ** 2 / 100.0)
    log_prob = -0.5 * np.sum(theta ** 2) + log_prior
    return log_prob, log_prior

coords = np.random.randn(32, 5)
nwalkers, ndim = coords.shape

filename = "tutorial.h5"
backend = emcee.backends.HDFBackend(filename)
backend.reset(nwalkers, ndim)

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend)
sampler.run_mcmc(coords, 100)

new_backend = emcee.backends.HDFBackend(filename)
print("Initial size: {0}".format(new_backend.iteration))
new_sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=new_backend)
new_sampler.run_mcmc(None, 200)
print("Final size: {0}".format(new_backend.iteration))

TERMINAL OUTPUT:
Initial size: 100
Final size: 300

**Comment by lorenzozanisi** [comment]
Hi, same problem here. @Sketos have you found a workaround for this?

**Comment by dfm** [comment]
I'm not sure I understand. This *is* the expected behavior. `run_mcmc` will always try to run for the requested number of steps. If you want a total of 200 steps, use `new_sampler.run_mcmc(None, 200 - new_backend.iteration)`.

**Comment by afoschi** [comment]
Hello, I'm running exactly the same case as @Sketos. I do expect the described behavior, but what is not clear to me is the way in which the autocorrelation time is computed at the end of the second run. 

In fact, at the end of the first run my sampler had size 270000 (I have 15 parameters and 64 walkers) and the autocorrelation time was too short for 2 parameters. For this reason I added 150000 iterations more and I expected the chain to converge (the final size is 420000), instead now the autocorrelation time is too short for 15 parameters. How can it be since the chain is longer? 

Thank you.

**Comment by dfm** [comment]
This is not the same issue. The issue that you're seeing @afoschi, is that the autocorrelation time calculation is noisy and depends on the chain sampled so far. This means that sometimes it will be underestimated with a short chain and it's not that uncommon to find behavior like you're seeing. Unfortunately there's no magic bullet for making sure that the autocorrelation time is always correct without running an effectively infinitely long chain.
