### ISSUE TITLE
save a side-product obtained in log_likelihood

### ISSUE THREAD

**Issue by wenbinlu** [dfm/emcee#340]
**General information:**

- emcee version: 3.0.2
- platform: MacOS
- installation method (pip/conda/source/other?): conda

**Problem description:**

The likelihood for parameter p_vector is given by the function "log_prob". At the same time, I would like to save another variable A obtained by my function "log_prob" when a set of parameters p_vector is accepted. I don't want to save A when p_vector is not accepted.

An inefficient way of doing this is that I obtain the full samples of p_vector first, and then calculate A for each of the sample separately. However, this would cost twice of the time (since I had obtained A for each sample during the emcee run but it was discarded).

### What have you tried so far?:

I added an extra element to my parameter array p_vector (so its dimension becomes ndim + 1). The final likelihood does not depend on this extra element. Each time when executing log_prob, I'm passing the wanted value A to the last element of p_vector by p_vector[-1] = A. I was hoping that emcee would save all this value p_vector[-1] in the final "###.h5" file. However, since p_vector is not a global variable (and it is not passed to log_prob by its reference), my A value is lost.

A sketch of the code is:

A = 0.   # initialize to an arbitrary value
pvec0 = np.array([p0, p1, p2, ..., A])    # initial position of a Ndim+1 vector
radius = 0.03
pvec_init = np.zeros((Nwalkers, Ndim+1))
for i in range(Nwalkers):
    pvec_init[i] = pvec0 + np.random.rand(Ndim+1)*radius

def log_prob(pvec):
      ## calculate the probability "P" ##
      ## at the same time I got "A" for this pvec ##
      pvec[-1] = A
      return log(P)

fpath = './test.h5'
backend = emcee.backends.HDFBackend(fpath)
backend.reset(Nwalkers, Ndim+1)
sampler = emcee.EnsembleSampler(Nwalkers, Ndim+1, ln_prob, backend=backend)
Nruns = 30
sampler.run_mcmc(pvec_init, Nruns)

**Comment by dfm** [comment]
Take a look at "blobs": https://emcee.readthedocs.io/en/stable/user/blobs/

These should do exactly what you want!
