### ISSUE TITLE
Broken link for autocorr time

### ISSUE THREAD

**Issue by cfhammill** [dfm/emcee#344]
The link at https://github.com/dfm/emcee/blob/e13edcb37174fa620bd7d4b8327dd36fe6385096/src/emcee/autocorr.py#L51

appears to be broken.

**Comment by dfm** [comment]
Brutal. This is a link that still works:

https://www.semanticscholar.org/paper/Monte-Carlo-Methods-in-Statistical-Mechanics%3A-and-Sokal/0bfe9e3db30605fe2d4d26e1a288a5e2997e7225

or

https://pdfs.semanticscholar.org/0bfe/9e3db30605fe2d4d26e1a288a5e2997e7225.pdf

**Comment by cfhammill** [comment]
Thanks!

**Comment by dfm** [comment]
Thank you! Let's keep this open so I remember to fix the link.
