### ISSUE TITLE
long double tests fail on ppc64el

### ISSUE THREAD

**Issue by mwhudson** [dfm/emcee#353]
**General information:**

- emcee version: 3.0.2
- platform: ppc64el
- installation method (pip/conda/source/other?): Ubuntu/Debian package

**Problem description:**

Version 3.0.2 of emcee is not migrating to the release pocket of Ubuntu because tests are failing on ppc64el: https://autopkgtest.ubuntu.com/packages/e/emcee/groovy/ppc64el

### Expected behavior

tests pass

### Actual behavior: 

test_longdouble_actually_needed[TempHDFBackend] and test_longdouble_preserved[TempHDFBackend] fail:

```
_______________ test_longdouble_actually_needed[TempHDFBackend] ________________

cls = <class 'emcee.backends.hdf.TempHDFBackend'>

    @pytest.mark.parametrize("cls", [emcee.backends.Backend,
                                     emcee.backends.TempHDFBackend])
    def test_longdouble_actually_needed(cls):
    
        mjd = np.longdouble(58000.)
        sigma = 100*np.finfo(np.longdouble).eps*mjd
    
        def log_prob(x):
            assert x.dtype == np.longdouble
            return -0.5 * np.sum(((x-mjd)/sigma) ** 2)
    
        ndim, nwalkers = 1, 20
        steps = 1000
        p0 = sigma*np.random.randn(nwalkers, ndim).astype(np.longdouble) + mjd
        assert not all(p0 == mjd)
    
        with cls(dtype=np.longdouble) as backend:
            sampler = emcee.EnsembleSampler(nwalkers,
                                            ndim,
                                            log_prob,
                                            backend=backend)
            sampler.run_mcmc(p0, steps)
    
            samples = sampler.get_chain().reshape((-1,))
>           assert samples.dtype == np.longdouble
E           AssertionError: assert dtype('<f8') == <class 'numpy.float128'>
E            +  where dtype('<f8') = array([ 5.80000000e+04, -4.60105223e-27,  5.80000000e+04, ...,\n       -6.24580733e-26,  5.80000000e+04, -7.38930048e-27]).dtype
E            +  and   <class 'numpy.float128'> = np.longdouble
```

(the other failure is similar)

### What have you tried so far?

Googling and getting a headache :)

I know that "long double" on PowerPC / POWER is a strange pair-of-64-bit-doubles type so I'm not surprised that it's on POWER that I see the problem. I also see from searching that hd5/h5py/numpy have a history of problems in this area (e.g. https://github.com/h5py/h5py/issues/817) so I'm not sure what the resolution should be. Skipping these tests on ppc64el for now (maybe in an Ubuntu specific patch) might make sense -- it's not like the failure of these new tests indicates any kind of regression.

**Comment by dfm** [comment]
Thanks for reporting!

@aarchiba: Do you have any thoughts on this one?

**Comment by aarchiba** [comment]
So this is the more complicated of the tests, but the answer is that HDF5 does not support long doubles on this platform (alas) and then silently downgrades the data to float (hey! what!?). I think if people use long doubles it's because they know they need them so silent downgrading is a disaster and thus we should raise an exception if trying to store long doubles in HDF5, but really that's the job of the HDF5 library so it may not make sense for `emcee` to try to cover for it. My recommendation is:

- Check whether HDF5 supports storing and recovering long doubles and set a flag HDF5_LONG_DOUBLE_SUPPORT
- Either:
    - If the flag is set skip these tests, or
    - If the flag is set check that an exception is raised when trying to store long doubles

Obviously the last situation would require changes to the code base of `emcee` as well.

**Comment by aarchiba** [comment]
Just to check but test_hdf5_dtypes does *not* fail?

**Comment by aarchiba** [comment]
Sorry I missed the link to the logs. Indeed `test_hdf5_dtypes` does fail, in the expected way.
