### ISSUE TITLE
Emits numpy deprecation warning about ragged sequences

### ISSUE THREAD

**Issue by aarchiba** [dfm/emcee#361]
**General information:**

- emcee version: 3.0.3.dev5+g87c4c85.d20200818
- platform: Linux
- installation method (pip/conda/source/other?): pip

**Problem description:**

Currently the way `emcee` packs blobs into its storage array risks incompatibility with future versions of `numpy` - or at least it triggers a DeprecationWarning. The basic problem is that `src/emcee/ensemble.py` tries to figure out the right dtype with `atleast_1d`:

```python
            # Get the blobs dtype
            if self.blobs_dtype is not None:
                dt = self.blobs_dtype
            else:
                try:
                    dt = np.atleast_1d(blob[0]).dtype
                except ValueError:
                    dt = np.dtype("object")
            blob = np.array(blob, dtype=dt)
```

The current behaviour will let users return lists/tuples of numbers and have them converted to extra dimensions on a numeric blobs array; this will come to grief if the lengths of those lists/tuples ever change or if the types change. But in the vast majority of cases the user probably wants numeric arrays rather than object arrays even if they just do `return 2, 3`. That said strings will make it very unhappy. Correct behaviour is unclear.

### Expected behavior:

`emcee` test suite completes without warnings.

### Actual behavior:

`emcee` test suite emits `numpy.VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray`

### Minimal example:

```
pytest -Werror src/emcee/tests/unit/test_blobs.py
```

**Comment by dfm** [comment]
Interesting! Yeah - the blobs type inference has always been a bit of a kludge and not totally satisfying.

Two possible approaches:

1. Re-implement and use something like [infer_dtype](https://github.com/pandas-dev/pandas/blob/3b0f23ad6825590c30212f0da593752b65db0bd6/pandas/_libs/lib.pyx#L1205) from pandas to keep the existing behavior (or something close), or
2. Add our own deprecation warning and require passing `blobs_dtype` whenever blobs are used.

**Comment by aarchiba** [comment]
I think a third option might be to permit blobs that were arrays (or floats) to have dtypes automatically inferred, and require deprecation warnings for sequences or other objects. That should cover the majority of blobs use cases, I think? Or one could go further and handle some obvious non-array cases - floats, strings, byte strings? Or just HDF5-able things?

**Comment by aarchiba** [comment]
The normal situation for `log_prob` seems to be to either return a float (no blob) or to return a tuple, of which everything but the first makes up the `blobs`, then everything is squeezed. So, like, maybe deal with a top-level tuple/list specially?

Most compatible option is to just ensure that the easy cases don't emit the warning, and leave the awkward cases with the same logic we use now, possibly emitting a more helpful warning message instead.

**Comment by aarchiba** [comment]
Strings are weird, and probably broken too - you get an array of Unicode strings of length equal to the longest string in the first blob produced. Longer strings that occur in later blobs will be silently truncated. Ditto byte strings.

I mean I guess nobody is using bare strings or there would be bug reports?

Seems to me that strings without an explicit `blobs_dtype` need to be in object arrays.
