### ISSUE TITLE
OpenMPI (60 cores) slower then local 4 cores

### ISSUE THREAD

**Issue by carlosRmelo** [dfm/emcee#366]
**General information:**
I'm trying to run emcee over 3 nodes each with 20 cores (multithreading, only physical cores) and each step takes ~220s/it. But, using multiprocessing in my personal computer with only 4 cores, each step taks ~89s/it.

- emcee version: 3.0.2
- python version: 3.6
- platform: linux
- installation method (pip/conda/source/other?):pip

**Problem description:**

So, my code follows the ideia of MPI paralelization describe here (https://emcee.readthedocs.io/.../tutorials/parallel/...). Then, to submit the job through slurm I use the flags presents in the image attached.
Each cluster node has 20 physical cpu's with 2 thread each, but I only want to use the physical cores.
When finally i submit the job via sbacth, everything looks good (squeue -j shows that 3 nodes are in use, and if i go to each node and type top -u $USER i can see 20 process in each node).
The problem is:
In my computer, using only 4 cores and running via:
mpirun python main_code.py
each step takes 89s/it.
But in the cluster (in principle using 60 cores) each step takes long 220s/it.
In principle i thought that the problem was maybe the inter node communication, but using only one node with 20 cores, the problem still appears.

Any help is welcome. Thanks in advance.

PS: I also tried to use the command:
mpirun -n 60 python main_code.py
But the result is the same as i have describe above.

PS2: module add openmpi loads openmpi/3.1.6-gcc-8.3.0

### Minimal example:

```python
import emcee
from schwimmbad import MPIPool

os.environ["OMP_NUM_THREADS"] = "1"

##read some data

##define log_probabilities
def log_probability(pars):


# sample code goes here...
with MPIPool() as pool:

    if not pool.is_master():
        pool.wait()
        sys.exit(0)


    np.random.seed(42)   

    beta = np.array([-0.0, 0.91, -0.9, -1.7, 0.43, -0.35, 0.32])
    beta_std = np.ones(beta.shape)*np.array(prior['beta1'][1])

   
    log_rho_s = np.array([10])
    log_rho_s_std = np.ones(log_rho_s.shape)*2

    

    ##Here we append all the variables and stds in a single array.
    p0 = np.append(beta, log_rho_s)


    p0_std = np.append(beta_std, log_rho_s_std)
    

    #Finally we initialize the walkers with a gaussian ball
    nwalkers = 200                                                  #Number of walkers
    pos = emcee.utils.sample_ball(p0, p0_std, nwalkers)             #Initial position of all walkers


    nwalkers, ndim = pos.shape
    print(ndim)

    filename = "save.h5"
    backend = emcee.backends.HDFBackend(filename)
    backend.reset(nwalkers, ndim)
    

    print("Number of Workers:", pool.workers)
    print("Start")
    
    
     # Initialize the sampler
    sampler = emcee.EnsembleSampler(nwalkers, ndim, log_probability, pool=pool, backend=backend)
    
    nsteps = 50000
    
    start = time.time()
    global_time = time.time()
    sampler.run_mcmc(pos, nsteps, progress=True)

    



```
![Screenshot from 2020-11-16 17-06-18](https://user-images.githubusercontent.com/64919772/99403245-01488700-28c9-11eb-9913-5f74f542c386.png)

**Comment by dfm** [comment]
This probably has something to do with the details of your model. For example, the numpy on your personal machine might be using more optimized linear algebra libraries. It would be worth benchmarking your model evaluation (not via emcee - just the model) on a single CPU on your cluster vs on your personal machine. My prediction is that the difference will be the same.

**Comment by carlosRmelo** [comment]
Thank you very much for hint. I just executed a run of the pure model, and yes, takes 5x time then in my computer. And during the chain this probably scales terribly.

I'm closing the issue. Thank you again.
