### ISSUE TITLE
Issues with Backend: Unable to extract mcmc chain info from a saved HDF5 file

### ISSUE THREAD

**Issue by ojashvirautela** [dfm/emcee#367]
**General information:**

- emcee version: 3.0.2
- platform: Jupyter notebook
- installation method (pip/conda/source/other?):  pip

**Problem description:**

### Expected behavior: 

Be able to Extract the chain information when saved using h5py backends

### Actual behavior:

 Whenever I try to extract the chain from the saved .h5 file I get the following error: "AttributeError: You must run the sampler with 'store == True' before accessing the results"

### What have you tried so far?: 

I tried to emulate the example from https://emcee.readthedocs.io/en/stable/tutorials/monitor/  (and this worked perfectly), also reinstalled : emcee, h5py library...

### Minimal example:

```python
import emcee
# sample code goes here...

def main(p0,nwalkers,niter,ndim,lnprob,data):
    
    filename="MCMC_dt2.h5"
    backend = emcee.backends.HDFBackend(filename, name="MCMC_dt2.h5")
    backend.reset(nwalkers, ndim)
    
    with Pool(6) as pool:
        sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=data,backend=backend, pool=pool)
    
        sampler.run_mcmc(p0,niter,progress=True, store = True)

    return sampler

sampler = main(p0,nwalkers,niter,ndim,lnprob,data)

reader = emcee.backends.HDFBackend("MCMC_dt2.h5")
samples = reader.get_chain(flat=True)    # this line gives the error shown below


```
![Screen Shot 2020-11-22 at 3 19 54 PM](https://user-images.githubusercontent.com/16581371/99920096-2fb5d000-2cd6-11eb-910f-9a9b5d9e15a3.png)

**Comment by dfm** [comment]
You're going to need to provide the same `name` both times. When you first set up the backend you use:

```python
backend = emcee.backends.HDFBackend(filename, name="MCMC_dt2.h5")
```

but the second time it's:

```python
reader = emcee.backends.HDFBackend("MCMC_dt2.h5")
```

So it's trying to read from the default extension called `mcmc`. Either leave it off the first time or use the argument `name="MCMC_dt2.h5"` the second time!

**Comment by ojashvirautela** [comment]
It worked! Thank you so much! :)
