### ISSUE TITLE
Integer Moves

### ISSUE THREAD

**Issue by SwastikC** [dfm/emcee#387]
Hi dfm,
Is there any method by which I can generate only integer moves in the walker. I am shifting a image pixel by pixel and my pixel values have to be integers in both x and y direction. Is there any way where my moves will always take integer steps. Also is there any way where I can choose if one of the parameter will take integer steps while the other will take floating value steps?

**Comment by dfm** [comment]
This is not supported - your best bet is to just round the pixel parameters to an integer value.

**Comment by SwastikC** [comment]
Oh yes yes !! Thanks dfm. It is working now :)
