### ISSUE TITLE
 RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by Nicolo97** [dfm/emcee#388]
**General information:**

- emcee version: 3.0.2

**Problem description:**
I'm using emcee to obtain 3 parameters at the same time with a chi_square like probability function. I do not know what this error mean in term of the run, because the run end as fine but this shows up.

emcee\moves\red_blue.py:99: RuntimeWarning: invalid value encountered in double_scalars
  lnpdiff = f + nlp - state.log_prob[j]

### What have you tried so far?:
Seeing the error I've tried to work on "moves" inside the sampler but didin't work out, so i belive maybe is something related to the prior.

### Minimal example:
The probability function is implemented like that:

def log_prior(theta):
    b, f, s = theta
    if b<0.1 or b>10.0 or f<0.1 or f>10.0 or s<0.1 or s>10.0:
        return 0.0
    return -np.inf

def log_prob(theta, x, y):
    lp = log_prior(theta)
    if not np.isfinite(lp):
        return -np.inf
    return lp + log_like(theta, x, y)

Where "log_like" is my chi_square like function.

Thanks in advance.

**Comment by dfm** [comment]
Please provide an *executable* piece of code that reproduces the issue that you're finding.

**Comment by Nicolo97** [comment]
The problem is that it requires reading some data files that I have on my pc.

**Comment by dfm** [comment]
Unfortunately you haven't provided enough information for me to help you out here. Please feel free to post a proper bug report in the future or reopen this issue if you are willing to take more time to properly diagnose.
