### ISSUE TITLE
issue with the documentation of emcee.autocorr.integrated_time

### ISSUE THREAD

**Issue by gica3618** [dfm/emcee#390]
**General information:**

- emcee version: 3.0.2
- platform: Ubuntu 18.04
- installation method (pip/conda/source/other?): conda

**Problem description:**
 
The documentation of emcee.autocorr.integrated_time (https://emcee.readthedocs.io/en/stable/user/autocorr/?highlight=get_autocorr#emcee.autocorr.integrated_time) says that an `axis` keyword can be used to specify the time axis. However, the method seems not to accept such a keyword; it results in TypeError: integrated_time() got an unexpected keyword argument 'axis'.
The method seems working even for multi-dimensional input, but in such a case it is unclear which axis is interpreted as the time axis.
The link to "Sokal's notes" seems also broken.

**Comment by gica3618** [comment]
Ok just realised that this is a copy of #337. I leave it open because of the broken link to Sokal's notes.

**Comment by dfm** [comment]
Thanks! I'm going to close this because the link is already fixed (https://github.com/dfm/emcee/pull/345) and you can see the fixed version here: https://emcee.readthedocs.io/en/latest/user/autocorr/ although the PDF is a bit of a pain to access.
