### ISSUE TITLE
chain.shape not consistent

### ISSUE THREAD

**Issue by gdrouart** [dfm/emcee#391]
**General information:**

- emcee version: 3.0.2
- platform: MacOS 10.14.6
- installation method (pip/conda/source/other?): pip

**Problem description:**
The chain shape is not identical when called back from backendHDF. 

### Expected behavior:
I run a model with say 20 walkers, 22 steps and 2 dimensions. if I run emcee and plot (by looping on the chain) at the same time, all good, and the chain have the shape (20, 22, 2). I would expect that when I load the chain from the hd5 file, the shape would be identical, and use the same plotting routine. Nope. 

### Actual behavior:
the shape of the chain from the .get_chain(), is now (22,20,2), the walkers and iterations dimensions are swapped. 

### What have you tried so far?:
I try to look into the source file to see if an assignation was swapped or something happen during the reading of the saved hd5, no success so far. I will try to look at reshaping array, which should be doable, but a bit frustrating.

### Minimal example:
Using the manual https://emcee.readthedocs.io/en/stable/tutorials/monitor/ I can reproduce the pb

```python
import emcee
import numpy as np

np.random.seed(42)

# The definition of the log probability function
# We'll also use the "blobs" feature to track the "log prior" for each step
def log_prob(theta):
    log_prior = -0.5 * np.sum((theta - 1.0) ** 2 / 100.0)
    log_prob = -0.5 * np.sum(theta ** 2) + log_prior
    return log_prob, log_prior


# Initialize the walkers
coords = np.random.randn(32, 5)
nwalkers, ndim = coords.shape

# Set up the backend
# Don't forget to clear it in case the file already exists
filename = "tutorial.h5"
backend = emcee.backends.HDFBackend(filename)
backend.reset(nwalkers, ndim)

# Initialize the sampler
sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend)

max_n = 200

# Now we'll sample for up to max_n steps
for sample in sampler.sample(coords, iterations=max_n, progress=True):
    # Only check convergence every 100 steps
    if sampler.iteration % 100:
        continue

reader = emcee.backends.HDFBackend(filename)
print(reader.get_chain().shape)
print(sampler.chain.shape)

```

**Comment by dfm** [comment]
The `.chain` attribute is deprecated and it only has that shape for backwards compatibility with old versions of emcee. New code should *always* use the `get_chain()` method which has the same shape as the backend.

**Comment by dfm** [comment]
P.S. if you want to reshape to get the `.chain` shape, here's how emcee does it:

https://github.com/dfm/emcee/blob/f0489d74250e2034d76c3a812b9afae74c9ca191/src/emcee/ensemble.py#L485-L489

so it's not so frustrating :D

**Comment by gdrouart** [comment]
Was late yesterday and a long day. Apologies if the tone was a bit harsh... will update everything accordingly, thanks for the precisions and clarifications!
