### ISSUE TITLE
AttributeError: module 'emcee' has no attribute 'backends'

### ISSUE THREAD

**Issue by Nicolo97** [dfm/emcee#394]
**General information:**

- emcee version: 3.1
- platform: linux
- installation method (pip/conda/source/other?): pip

**Problem description:**
AttributeError: module 'emcee' has no attribute 'backends'
### Expected behavior:
I'm now trying to work by remote in to a linux machine and does not work but when i use it on my windows device this error do not show up, I do not understad.

**Comment by dfm** [comment]
You must have an old version of emcee installed so try uninstalling and upgrading.

**Comment by Nicolo97** [comment]
I've installed the latest 3.1 so I do not understand.

**Comment by dfm** [comment]
Well version 3.1 has a `backends` submodule so I'm pretty sure you didn't :D

But more seriously: `pip` can sometimes end up with issues with uninstalling old versions of packages and you can end up with colliding namespaces. So you should try *uninstalling all installed versions of emcee* and starting again. I can confirm that a freshly installed version of 3.1 works just fine on several different linux platforms.
