### ISSUE TITLE
Saving Chain with multiprocessing

### ISSUE THREAD

**Issue by mayamkay** [dfm/emcee#403]
**General information:**

- emcee version: 3.1.0
- platform: mac
- installation method (pip/conda/source/other?): conda forge

**Problem description:**
I'm trying to find a way to use multiprocessing but also save steps of the chain such that if the run crashes or doesn't converge I can continue running it from where it left off. I've been trying to do this using backends and pool but it seems the two aren't compatible. Is there an alternative approach? 
### Expected behavior:
Save emcee chain using backends with pool

### Actual behavior:
The file can't be accessed by the different threads so it fails

### Minimal example:

<
from multiprocessing import Pool

with Pool() as pool:
    sampler = emcee.EnsembleSampler(Nens, ndims, logposterior, args=argslist, pool=pool, backend=backend)) #
    start = time.time()
    
    sampler.run_mcmc(inisamples, Nsamples + Nburnin)
    
    end = time.time()
    multi_time = end - start
    print("Multiprocessing took {0:.1f} seconds".format(multi_time))
>

**Comment by dfm** [comment]
The backend and pool are definitely compatible - that's a very common use case and the backend only runs on the main thread. Please share an _executable_ snippet of code (the one you shared is missing a lot of definitions) that reproduces the issue you're seeing.

**Comment by dfm** [comment]
Thanks - that runs just fine on my Mac and on Google colab. It looks like you're launching with slurm so I bet you're running the same script multiple times in parallel by mistake and trying to write to the same file in parallel. I'm not sure that I can be super helpful with your specific environment setup, but I'd look into exactly how you're launching the script and how you're managing resources. Hope this helps!

**Comment by mayamkay** [comment]
Thanks so much for the help I really appreciate it. I'll try to fix the way I'm launching the script then!

**Comment by mayamkay** [comment]
For the sake of anyone else looking into this it turns out that running with HDF5 files in cori's $HOME tends to throw this issue. I switched to $SCRATCH and then it ran fine. Thanks again dfm for helping me trouble shoot this!
