### ISSUE TITLE
The parameter values looks repeating in the chains

### ISSUE THREAD

**Issue by WeakDog** [dfm/emcee#420]
Hello,

I'm now using the emcee and just found that the chains look weird where the parameter values appear to be repeated in the chains. I attach the figure showing the parameters as a function of the steps in the chain below. I was wondering whether this is reasonable or not. Thanks!

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/30678982/161238769-bcb38388-02b7-483c-949d-bbcb7279b89e.png">

**Comment by dfm** [comment]
This looks like a plotting issue to me. Take a look at the docs for an example of how to plot your traces: e.g. https://emcee.readthedocs.io/en/stable/tutorials/line/#marginalization-uncertainty-estimation

**Comment by WeakDog** [comment]
Many thanks for your help!
