### ISSUE TITLE
Walkers apparently clustering in points of low likelihood

### ISSUE THREAD

**Issue by Chris-Pedersen** [dfm/emcee#423]
**General information:**
Islands forming when sampling

- emcee version:  3.1.1
- platform:
- installation method (pip/conda/source/other?): pip

**Problem description:**
I'm getting these islands appearing after running emcee on my likelihood function, far from the maximum likelihood. I'm confident these are not features of the likelihood space due to the fact that when running the exact same config multiple times, they appear in different places, and when forcing the chains to run for significantly longer than autocorrelation time convergence, most of the time they disappear. Sometimes they don't though. Also when plotting likelihood scans, the likelihood function always looks smooth. Example below, running the exact same config multiple times:
![islands](https://user-images.githubusercontent.com/16047009/163209923-8a17e29f-927c-459a-86cc-4623cdba1ca3.png)

I have tried restricting the prior volume to reduce this, but we are currently at the tightest priors that our analysis permits and still see them. Any thoughts on what's going on would be much appreciated!

**Comment by dfm** [comment]
Hi Chris - This isn't that uncommon and it's generally the result of poor initialization. Emcee often isn't great at finding the mode, so it can be useful to use an optimizer to find a sensible initialization (like in [this tutorial](https://emcee.readthedocs.io/en/stable/tutorials/line/)). Sometimes that isn't sufficient and you can define a burn-in procedure where (during burn-in) you occasionally resample the walkers near the maximum probability sample seen so far.
