### ISSUE TITLE
How to fix my model to specfic points？

### ISSUE THREAD

**Issue by Gade-Z** [dfm/emcee#428]

**Comment by Gade-Z** [comment]
<img width="338" alt="Screen Shot 2022-05-18 at 11 13 16" src="https://user-images.githubusercontent.com/56994196/168949710-9ac99281-62ae-45d6-9df0-78db0376f6a5.png">
As the figure shows, the red curve is the model and green is the observed data, I want to fit the model to the data and ensure that the model can reproduce the 2 peaks of the observed data, this requires me to let the model be fixed to fit through the peak points. How can I do this? Thanks。

**Comment by dfm** [comment]
This isn't an emcee issue so I'm going to close this. If you email the emcee mailing list with more details someone might be able to help, but I'm not sure if that's the best resource either. But hopefully someone can point you in the right direction!
