### ISSUE TITLE
Multiprocessing Pool scaling not as expected

### ISSUE THREAD

**Issue by HannoJJacobs** [dfm/emcee#452]
**General information:**

- emcee version: 3.1.2 (numpy 1.24.0)
- platform: Lenovo ThinkPad X250 with Ubuntu 22.04.1 LTS
- installation method (pip/conda/source/other?): pip

**Problem description:**

I have written a mock example of a MCMC scan which **mainly waits one second** to check the speedup for a compute proposal.
What I found surprised me a lot.

### Expected behavior: If I use 6 walkers and 10 steps, I expect the time to decrease with more cores in the following manner:
1 core: 60sec
2 core: 30sec
3 core: 20sec
all above are identical since (if I understand correctly) the maximum is nwalker/2. 

### Actual behavior:
1 core: 60sec
2 core: **40sec**
3 core: 20sec

### Minimal example: (comand line arguments are : ncores, nwalkers, nsteps)

```
import numpy as np
import emcee
import os
from multiprocessing import Pool
import sys
import time
sb=0.04

def lin(x,q):
	return x**q+50
def blin(x,xb,qh,ql,x0):
	result= (1+(x/xb)**(-1/sb))**(-sb*(ql-qh))*x**qh+x0
	return result
q_real=1
xmin=10**(-2); xmax=10**2
x=np.logspace(np.log10(xmin),np.log10(xmax),10000)
sigma_model=lin(x,q_real)*0.2
yerr=sigma_model
model_mean=lin(x,q_real)
np.random.seed(0)
model_mock=np.random.normal(model_mean,sigma_model)

if __name__=="__main__":
	args=sys.argv[1:]
	ncores=int(args[0])
	nwalkers= int(args[1])
	nsteps= int(args[2])
	ndim=3
	st = time.time()
	def log_likelihood(theta):
		x0,ql,xb = theta
		model=blin(x,xb,q_real,ql,x0)	
		sigma2 = yerr**2 												
		result=-0.5 * np.sum((model_mock - model) ** 2 / sigma2)
		time.sleep(1)
		et = time.time()
		print("time in sec=",et-st,"pid:",os.getpid())
		
		return result
	def log_prior(theta):
		x0,ql,xb = theta
		if xmin/10<xb<xmax and -4<ql<4 and 0<x0<100:
			return 0.0
		return -np.inf 
	def log_probability(theta):
		lp = log_prior(theta)
		if not np.isfinite(lp):
			return -np.inf
		return lp + log_likelihood(theta)
	sparam = np.array([10,q_real,3])
	pos = sparam * (1 + 1e-1 * np.random.randn(nwalkers, ndim))
	try:
		os.remove("test.h5")
	except OSError:
		pass
	backend = emcee.backends.HDFBackend("test.h5")
	backend.reset(nwalkers, ndim)
	with Pool(ncores) as pool:
		sampler = emcee.EnsembleSampler(nwalkers, ndim, log_probability, backend=backend, pool=pool)
		sampler.run_mcmc(pos, nsteps, progress=True,store = True);
```

**Comment by dfm** [comment]
I wouldn't expect the scaling to every be perfect with Python multiprocessing because of the intrinsic overhead. Furthermore, with 2 cores and 6 walkers it'll run two model evaluations in parallel, one in serial, and then synchronize before moving on to the second half. So to me, your results look fine!

**Comment by HannoJJacobs** [comment]
Thank you very much for your fast reply Dan!
Your explanation in itself makes sense.
I have two questions out of curiosity:
Why cant you use more than nwalker/2 cores?
And why this division in 3? (what prevents you from always running 2 of the 6 walkers in parallel?)
If you have a good reference, I am happy to read it.

**Comment by dfm** [comment]
The way the emcee parallelization algorithm works is that it updates half the walkers based on the current positions of the other half. This means that it'll never evaluate more than nwalkers/2 models in parallel. IIRC, this is described in the [emcee paper](https://arxiv.org/abs/1202.3665). Hope this helps!

**Comment by HannoJJacobs** [comment]
Great! 
Thanks a lot for the help and keep up the good work, I highly appreciate it.
